// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"time"
)

const countActiveSuperAdmins = `-- name: CountActiveSuperAdmins :one
SELECT COUNT(*)::bigint
FROM internal_users
WHERE deleted_at IS NULL
  AND is_active
  AND role = 'super_admin'
`

func (q *Queries) CountActiveSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSearchesInRange = `-- name: CountSearchesInRange :one
SELECT COUNT(*)::bigint
FROM search_queries
WHERE queried_at >= $1
  AND queried_at < $2
`

type CountSearchesInRangeParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

func (q *Queries) CountSearchesInRange(ctx context.Context, arg CountSearchesInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchesInRange, arg.RangeStart, arg.RangeEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardCoverage = `-- name: DashboardCoverage :one

SELECT
    (SELECT COUNT(*)::bigint
     FROM pharmacies
     WHERE deleted_at IS NULL
       AND status = 'active') AS active_pharmacies,
    (SELECT COUNT(*)::bigint
     FROM products
     WHERE deleted_at IS NULL
       AND status = 'published') AS published_products,
    (SELECT COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY EXTRACT(EPOCH FROM (now() - last_seen_at))), 0)::float8
     FROM offers
     WHERE status = 'active') AS median_freshness_seconds
`

type DashboardCoverageRow struct {
	ActivePharmacies       int64
	PublishedProducts      int64
	MedianFreshnessSeconds float64
}

// Dashboard, internal users, site settings and feature flags (super_admin).
func (q *Queries) DashboardCoverage(ctx context.Context) (DashboardCoverageRow, error) {
	row := q.db.QueryRow(ctx, dashboardCoverage)
	var i DashboardCoverageRow
	err := row.Scan(&i.ActivePharmacies, &i.PublishedProducts, &i.MedianFreshnessSeconds)
	return i, err
}

const listActivePharmaciesBrief = `-- name: ListActivePharmaciesBrief :many
SELECT id, slug, name
FROM pharmacies
WHERE deleted_at IS NULL
  AND status = 'active'
ORDER BY name
`

type ListActivePharmaciesBriefRow struct {
	ID   int64
	Slug string
	Name string
}

func (q *Queries) ListActivePharmaciesBrief(ctx context.Context) ([]ListActivePharmaciesBriefRow, error) {
	rows, err := q.db.Query(ctx, listActivePharmaciesBrief)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePharmaciesBriefRow{}
	for rows.Next() {
		var i ListActivePharmaciesBriefRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClickVolumeByDay = `-- name: ListClickVolumeByDay :many
SELECT date_trunc('day', clicked_at)::timestamptz AS day,
       COUNT(*)::bigint                           AS clicks
FROM redirect_clicks
WHERE clicked_at >= $1
  AND clicked_at < $2
GROUP BY 1
ORDER BY 1
`

type ListClickVolumeByDayParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListClickVolumeByDayRow struct {
	Day    time.Time
	Clicks int64
}

func (q *Queries) ListClickVolumeByDay(ctx context.Context, arg ListClickVolumeByDayParams) ([]ListClickVolumeByDayRow, error) {
	rows, err := q.db.Query(ctx, listClickVolumeByDay, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClickVolumeByDayRow{}
	for rows.Next() {
		var i ListClickVolumeByDayRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT id, key, pharmacy_id, enabled, updated_at
FROM feature_flags
ORDER BY key, pharmacy_id NULLS FIRST
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureFlag{}
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.PharmacyID,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrequentSearchesInRange = `-- name: ListFrequentSearchesInRange :many
SELECT query_normalized, COUNT(*)::bigint AS hits, MAX(queried_at) AS last_seen
FROM search_queries
WHERE queried_at >= $1
  AND queried_at < $2
GROUP BY query_normalized
ORDER BY hits DESC, last_seen DESC
LIMIT 50
`

type ListFrequentSearchesInRangeParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListFrequentSearchesInRangeRow struct {
	QueryNormalized string
	Hits            int64
	LastSeen        interface{}
}

func (q *Queries) ListFrequentSearchesInRange(ctx context.Context, arg ListFrequentSearchesInRangeParams) ([]ListFrequentSearchesInRangeRow, error) {
	rows, err := q.db.Query(ctx, listFrequentSearchesInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrequentSearchesInRangeRow{}
	for rows.Next() {
		var i ListFrequentSearchesInRangeRow
		if err := rows.Scan(&i.QueryNormalized, &i.Hits, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalUsers = `-- name: ListInternalUsers :many
SELECT id, username, role, is_active, created_at
FROM internal_users
WHERE deleted_at IS NULL
ORDER BY id
`

type ListInternalUsersRow struct {
	ID        int64
	Username  string
	Role      string
	IsActive  bool
	CreatedAt time.Time
}

func (q *Queries) ListInternalUsers(ctx context.Context) ([]ListInternalUsersRow, error) {
	rows, err := q.db.Query(ctx, listInternalUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInternalUsersRow{}
	for rows.Next() {
		var i ListInternalUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchVolumeByDay = `-- name: ListSearchVolumeByDay :many
SELECT date_trunc('day', queried_at)::timestamptz AS day,
       COUNT(*)::bigint                           AS searches
FROM search_queries
WHERE queried_at >= $1
  AND queried_at < $2
GROUP BY 1
ORDER BY 1
`

type ListSearchVolumeByDayParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListSearchVolumeByDayRow struct {
	Day      time.Time
	Searches int64
}

func (q *Queries) ListSearchVolumeByDay(ctx context.Context, arg ListSearchVolumeByDayParams) ([]ListSearchVolumeByDayRow, error) {
	rows, err := q.db.Query(ctx, listSearchVolumeByDay, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchVolumeByDayRow{}
	for rows.Next() {
		var i ListSearchVolumeByDayRow
		if err := rows.Scan(&i.Day, &i.Searches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteSettings = `-- name: ListSiteSettings :many
SELECT key, value, updated_at
FROM site_settings
ORDER BY key
`

func (q *Queries) ListSiteSettings(ctx context.Context) ([]SiteSetting, error) {
	rows, err := q.db.Query(ctx, listSiteSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZeroResultSearchesInRange = `-- name: ListZeroResultSearchesInRange :many
SELECT query_normalized, COUNT(*)::bigint AS hits, MAX(queried_at) AS last_seen
FROM search_queries
WHERE result_count = 0
  AND queried_at >= $1
  AND queried_at < $2
GROUP BY query_normalized
ORDER BY hits DESC, last_seen DESC
LIMIT 50
`

type ListZeroResultSearchesInRangeParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListZeroResultSearchesInRangeRow struct {
	QueryNormalized string
	Hits            int64
	LastSeen        interface{}
}

func (q *Queries) ListZeroResultSearchesInRange(ctx context.Context, arg ListZeroResultSearchesInRangeParams) ([]ListZeroResultSearchesInRangeRow, error) {
	rows, err := q.db.Query(ctx, listZeroResultSearchesInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZeroResultSearchesInRangeRow{}
	for rows.Next() {
		var i ListZeroResultSearchesInRangeRow
		if err := rows.Scan(&i.QueryNormalized, &i.Hits, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInternalUser = `-- name: UpdateInternalUser :exec
UPDATE internal_users
SET role          = $2,
    is_active     = $3,
    password_hash = COALESCE($4, password_hash)
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateInternalUserParams struct {
	ID           int64
	Role         string
	IsActive     bool
	PasswordHash *string
}

func (q *Queries) UpdateInternalUser(ctx context.Context, arg UpdateInternalUserParams) error {
	_, err := q.db.Exec(ctx, updateInternalUser,
		arg.ID,
		arg.Role,
		arg.IsActive,
		arg.PasswordHash,
	)
	return err
}

const upsertGlobalFlag = `-- name: UpsertGlobalFlag :exec
INSERT INTO feature_flags (key, pharmacy_id, enabled, updated_at)
VALUES ($1, NULL, $2, now())
ON CONFLICT (key) WHERE pharmacy_id IS NULL
    DO UPDATE SET enabled    = EXCLUDED.enabled,
                  updated_at = now()
`

type UpsertGlobalFlagParams struct {
	Key     string
	Enabled bool
}

func (q *Queries) UpsertGlobalFlag(ctx context.Context, arg UpsertGlobalFlagParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalFlag, arg.Key, arg.Enabled)
	return err
}

const upsertPharmacyFlag = `-- name: UpsertPharmacyFlag :exec
INSERT INTO feature_flags (key, pharmacy_id, enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key, pharmacy_id) WHERE pharmacy_id IS NOT NULL
    DO UPDATE SET enabled    = EXCLUDED.enabled,
                  updated_at = now()
`

type UpsertPharmacyFlagParams struct {
	Key        string
	PharmacyID *int64
	Enabled    bool
}

func (q *Queries) UpsertPharmacyFlag(ctx context.Context, arg UpsertPharmacyFlagParams) error {
	_, err := q.db.Exec(ctx, upsertPharmacyFlag, arg.Key, arg.PharmacyID, arg.Enabled)
	return err
}

const upsertSiteSetting = `-- name: UpsertSiteSetting :exec
INSERT INTO site_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE
    SET value      = EXCLUDED.value,
        updated_at = now()
`

type UpsertSiteSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertSiteSetting(ctx context.Context, arg UpsertSiteSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSiteSetting, arg.Key, arg.Value)
	return err
}
