// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerting.sql

package store

import (
	"context"
	"time"
)

const countActiveAlerts = `-- name: CountActiveAlerts :one
SELECT COUNT(*)::bigint
FROM price_alerts
WHERE user_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

func (q *Queries) CountActiveAlerts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlerts, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFavorite = `-- name: DeleteFavorite :exec
DELETE FROM favorites
WHERE user_id = $1
  AND product_id = $2
`

type DeleteFavoriteParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) error {
	_, err := q.db.Exec(ctx, deleteFavorite, arg.UserID, arg.ProductID)
	return err
}

const favoriteExists = `-- name: FavoriteExists :one
SELECT EXISTS (
    SELECT 1 FROM favorites WHERE user_id = $1 AND product_id = $2
) AS exists
`

type FavoriteExistsParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) FavoriteExists(ctx context.Context, arg FavoriteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, favoriteExists, arg.UserID, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAlertDelivery = `-- name: InsertAlertDelivery :execrows
INSERT INTO alert_deliveries (alert_id, event_key, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (alert_id, event_key) DO NOTHING
`

type InsertAlertDeliveryParams struct {
	AlertID  int64
	EventKey string
}

func (q *Queries) InsertAlertDelivery(ctx context.Context, arg InsertAlertDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAlertDelivery, arg.AlertID, arg.EventKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPriceAlert = `-- name: InsertPriceAlert :one
INSERT INTO price_alerts (user_id, product_id, kind, target_price_rial, baseline_price_rial, stock_was_available)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, product_id, kind, target_price_rial, baseline_price_rial, stock_was_available, status, created_at
`

type InsertPriceAlertParams struct {
	UserID            int64
	ProductID         int64
	Kind              string
	TargetPriceRial   *int64
	BaselinePriceRial int64
	StockWasAvailable bool
}

type InsertPriceAlertRow struct {
	ID                int64
	UserID            int64
	ProductID         int64
	Kind              string
	TargetPriceRial   *int64
	BaselinePriceRial int64
	StockWasAvailable bool
	Status            string
	CreatedAt         time.Time
}

func (q *Queries) InsertPriceAlert(ctx context.Context, arg InsertPriceAlertParams) (InsertPriceAlertRow, error) {
	row := q.db.QueryRow(ctx, insertPriceAlert,
		arg.UserID,
		arg.ProductID,
		arg.Kind,
		arg.TargetPriceRial,
		arg.BaselinePriceRial,
		arg.StockWasAvailable,
	)
	var i InsertPriceAlertRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Kind,
		&i.TargetPriceRial,
		&i.BaselinePriceRial,
		&i.StockWasAvailable,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAlertsForEval = `-- name: ListActiveAlertsForEval :many
SELECT a.id, a.user_id, a.product_id, a.kind, a.target_price_rial, a.baseline_price_rial,
       a.stock_was_available, u.phone, p.name_fa AS product_name
FROM price_alerts a
         JOIN users u ON u.id = a.user_id AND u.deleted_at IS NULL
         JOIN products p ON p.id = a.product_id AND p.deleted_at IS NULL
WHERE a.status = 'active'
  AND a.deleted_at IS NULL
`

type ListActiveAlertsForEvalRow struct {
	ID                int64
	UserID            int64
	ProductID         int64
	Kind              string
	TargetPriceRial   *int64
	BaselinePriceRial int64
	StockWasAvailable bool
	Phone             string
	ProductName       string
}

func (q *Queries) ListActiveAlertsForEval(ctx context.Context) ([]ListActiveAlertsForEvalRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsForEval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertsForEvalRow{}
	for rows.Next() {
		var i ListActiveAlertsForEvalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Kind,
			&i.TargetPriceRial,
			&i.BaselinePriceRial,
			&i.StockWasAvailable,
			&i.Phone,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavorites = `-- name: ListFavorites :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1)::int AS offer_count,
       f.created_at
FROM favorites f
         JOIN products p ON p.id = f.product_id AND p.deleted_at IS NULL AND p.status = 'published'
         LEFT JOIN offers o ON o.product_id = p.id
WHERE f.user_id = $2
GROUP BY p.id, f.created_at
ORDER BY f.created_at DESC
`

type ListFavoritesParams struct {
	FreshSince time.Time
	UserID     int64
}

type ListFavoritesRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	LowestPriceRial int64
	OfferCount      int32
	CreatedAt       time.Time
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, arg.FreshSince, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductQuotes = `-- name: ListProductQuotes :many
SELECT p.id AS product_id,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock), 0)::bigint AS lowest_in_stock_rial,
       COALESCE(BOOL_OR(o.in_stock) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), FALSE)::bool AS in_stock
FROM products p
         LEFT JOIN offers o ON o.product_id = p.id
WHERE p.id = ANY ($2::bigint[])
GROUP BY p.id
`

type ListProductQuotesParams struct {
	FreshSince time.Time
	ProductIds []int64
}

type ListProductQuotesRow struct {
	ProductID         int64
	LowestInStockRial int64
	InStock           bool
}

func (q *Queries) ListProductQuotes(ctx context.Context, arg ListProductQuotesParams) ([]ListProductQuotesRow, error) {
	rows, err := q.db.Query(ctx, listProductQuotes, arg.FreshSince, arg.ProductIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductQuotesRow{}
	for rows.Next() {
		var i ListProductQuotesRow
		if err := rows.Scan(&i.ProductID, &i.LowestInStockRial, &i.InStock); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryableDeliveries = `-- name: ListRetryableDeliveries :many
SELECT d.id, d.alert_id, d.event_key, d.attempts, a.user_id, a.product_id, a.kind, u.phone, p.name_fa AS product_name
FROM alert_deliveries d
         JOIN price_alerts a ON a.id = d.alert_id AND a.deleted_at IS NULL
         JOIN users u ON u.id = a.user_id AND u.deleted_at IS NULL
         JOIN products p ON p.id = a.product_id
WHERE d.status IN ('pending', 'failed')
  AND d.attempts < 5
ORDER BY d.id
LIMIT 200
`

type ListRetryableDeliveriesRow struct {
	ID          int64
	AlertID     int64
	EventKey    string
	Attempts    int32
	UserID      int64
	ProductID   int64
	Kind        string
	Phone       string
	ProductName string
}

func (q *Queries) ListRetryableDeliveries(ctx context.Context) ([]ListRetryableDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listRetryableDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetryableDeliveriesRow{}
	for rows.Next() {
		var i ListRetryableDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.EventKey,
			&i.Attempts,
			&i.UserID,
			&i.ProductID,
			&i.Kind,
			&i.Phone,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAlerts = `-- name: ListUserAlerts :many
SELECT a.id, a.user_id, a.product_id, a.kind, a.target_price_rial, a.baseline_price_rial,
       a.stock_was_available, a.status, a.created_at,
       p.slug AS product_slug, p.name_fa AS product_name
FROM price_alerts a
         JOIN products p ON p.id = a.product_id AND p.deleted_at IS NULL
WHERE a.user_id = $1
  AND a.deleted_at IS NULL
ORDER BY a.created_at DESC
`

type ListUserAlertsRow struct {
	ID                int64
	UserID            int64
	ProductID         int64
	Kind              string
	TargetPriceRial   *int64
	BaselinePriceRial int64
	StockWasAvailable bool
	Status            string
	CreatedAt         time.Time
	ProductSlug       string
	ProductName       string
}

func (q *Queries) ListUserAlerts(ctx context.Context, userID int64) ([]ListUserAlertsRow, error) {
	rows, err := q.db.Query(ctx, listUserAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAlertsRow{}
	for rows.Next() {
		var i ListUserAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Kind,
			&i.TargetPriceRial,
			&i.BaselinePriceRial,
			&i.StockWasAvailable,
			&i.Status,
			&i.CreatedAt,
			&i.ProductSlug,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE alert_deliveries
SET status     = 'failed',
    attempts   = attempts + 1,
    last_error = $2
WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID        int64
	LastError *string
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE alert_deliveries
SET status     = 'sent',
    attempts   = attempts + 1,
    sent_at    = now(),
    last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkDeliverySent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDeliverySent, id)
	return err
}

const publishedProductExists = `-- name: PublishedProductExists :one
SELECT EXISTS (
    SELECT 1 FROM products WHERE id = $1 AND deleted_at IS NULL AND status = 'published'
) AS exists
`

func (q *Queries) PublishedProductExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, publishedProductExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteAlert = `-- name: SoftDeleteAlert :execrows
UPDATE price_alerts
SET deleted_at = now(),
    status     = 'paused'
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteAlertParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SoftDeleteAlert(ctx context.Context, arg SoftDeleteAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAlert, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAlertBaseline = `-- name: UpdateAlertBaseline :exec
UPDATE price_alerts
SET baseline_price_rial = $2
WHERE id = $1
`

type UpdateAlertBaselineParams struct {
	ID                int64
	BaselinePriceRial int64
}

func (q *Queries) UpdateAlertBaseline(ctx context.Context, arg UpdateAlertBaselineParams) error {
	_, err := q.db.Exec(ctx, updateAlertBaseline, arg.ID, arg.BaselinePriceRial)
	return err
}

const updateAlertStockFlag = `-- name: UpdateAlertStockFlag :exec
UPDATE price_alerts
SET stock_was_available = $2
WHERE id = $1
`

type UpdateAlertStockFlagParams struct {
	ID                int64
	StockWasAvailable bool
}

func (q *Queries) UpdateAlertStockFlag(ctx context.Context, arg UpdateAlertStockFlagParams) error {
	_, err := q.db.Exec(ctx, updateAlertStockFlag, arg.ID, arg.StockWasAvailable)
	return err
}

const upsertFavorite = `-- name: UpsertFavorite :exec
INSERT INTO favorites (user_id, product_id)
VALUES ($1, $2)
ON CONFLICT (user_id, product_id) DO NOTHING
`

type UpsertFavoriteParams struct {
	UserID    int64
	ProductID int64
}

func (q *Queries) UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error {
	_, err := q.db.Exec(ctx, upsertFavorite, arg.UserID, arg.ProductID)
	return err
}
