// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_list.sql

package store

import (
	"context"
	"time"
)

const getPublishedCategoryBySlug = `-- name: GetPublishedCategoryBySlug :one
SELECT id, slug, name_fa, updated_at
FROM categories
WHERE slug = $1
  AND deleted_at IS NULL
`

type GetPublishedCategoryBySlugRow struct {
	ID        int64
	Slug      string
	NameFa    string
	UpdatedAt time.Time
}

func (q *Queries) GetPublishedCategoryBySlug(ctx context.Context, slug string) (GetPublishedCategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedCategoryBySlug, slug)
	var i GetPublishedCategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameFa,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProductsBySlugs = `-- name: GetPublishedProductsBySlugs :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1)::int AS offer_count,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock)::int AS in_stock_count
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN offers o ON o.product_id = p.id
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND p.slug = ANY ($2::text[])
GROUP BY p.id, b.name_fa
ORDER BY p.id
`

type GetPublishedProductsBySlugsParams struct {
	FreshSince time.Time
	Slugs      []string
}

type GetPublishedProductsBySlugsRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
}

func (q *Queries) GetPublishedProductsBySlugs(ctx context.Context, arg GetPublishedProductsBySlugsParams) ([]GetPublishedProductsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, getPublishedProductsBySlugs, arg.FreshSince, arg.Slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPublishedProductsBySlugsRow{}
	for rows.Next() {
		var i GetPublishedProductsBySlugsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCategorySlugs = `-- name: ListPublishedCategorySlugs :many
SELECT c.slug, c.updated_at
FROM categories c
WHERE c.deleted_at IS NULL
  AND EXISTS (SELECT 1
              FROM products p
              WHERE p.category_id = c.id
                AND p.deleted_at IS NULL
                AND p.status = 'published')
ORDER BY c.name_fa
LIMIT 5000
`

type ListPublishedCategorySlugsRow struct {
	Slug      string
	UpdatedAt time.Time
}

func (q *Queries) ListPublishedCategorySlugs(ctx context.Context) ([]ListPublishedCategorySlugsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCategorySlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCategorySlugsRow{}
	for rows.Next() {
		var i ListPublishedCategorySlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProducts = `-- name: ListPublishedProducts :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1)::int AS offer_count,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock)::int AS in_stock_count
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN offers o ON o.product_id = p.id
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
GROUP BY p.id, b.name_fa
ORDER BY p.id
LIMIT $2
`

type ListPublishedProductsParams struct {
	FreshSince time.Time
	PageLimit  int32
}

type ListPublishedProductsRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
}

func (q *Queries) ListPublishedProducts(ctx context.Context, arg ListPublishedProductsParams) ([]ListPublishedProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProducts, arg.FreshSince, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedProductsRow{}
	for rows.Next() {
		var i ListPublishedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProductsByCategorySlug = `-- name: ListPublishedProductsByCategorySlug :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1)::int AS offer_count,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock)::int AS in_stock_count
FROM products p
         JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN offers o ON o.product_id = p.id
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND c.slug = $2
GROUP BY p.id, b.name_fa
ORDER BY p.id
LIMIT $3
`

type ListPublishedProductsByCategorySlugParams struct {
	FreshSince   time.Time
	CategorySlug string
	PageLimit    int32
}

type ListPublishedProductsByCategorySlugRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
}

func (q *Queries) ListPublishedProductsByCategorySlug(ctx context.Context, arg ListPublishedProductsByCategorySlugParams) ([]ListPublishedProductsByCategorySlugRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProductsByCategorySlug, arg.FreshSince, arg.CategorySlug, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedProductsByCategorySlugRow{}
	for rows.Next() {
		var i ListPublishedProductsByCategorySlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
