// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_write.sql

package store

import (
	"context"
)

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, slug, name_fa, name_en
FROM brands
WHERE slug = $1
  AND deleted_at IS NULL
`

type GetBrandBySlugRow struct {
	ID     int64
	Slug   string
	NameFa string
	NameEn *string
}

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (GetBrandBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i GetBrandBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameFa,
		&i.NameEn,
	)
	return i, err
}

const getProductByGTIN = `-- name: GetProductByGTIN :one
SELECT id, slug, name_fa
FROM products
WHERE gtin = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProductByGTINRow struct {
	ID     int64
	Slug   string
	NameFa string
}

func (q *Queries) GetProductByGTIN(ctx context.Context, gtin *string) (GetProductByGTINRow, error) {
	row := q.db.QueryRow(ctx, getProductByGTIN, gtin)
	var i GetProductByGTINRow
	err := row.Scan(&i.ID, &i.Slug, &i.NameFa)
	return i, err
}

const getProductByIRC = `-- name: GetProductByIRC :one
SELECT id, slug, name_fa
FROM products
WHERE irc = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProductByIRCRow struct {
	ID     int64
	Slug   string
	NameFa string
}

func (q *Queries) GetProductByIRC(ctx context.Context, irc *string) (GetProductByIRCRow, error) {
	row := q.db.QueryRow(ctx, getProductByIRC, irc)
	var i GetProductByIRCRow
	err := row.Scan(&i.ID, &i.Slug, &i.NameFa)
	return i, err
}

const getProductByNormalizedName = `-- name: GetProductByNormalizedName :one
SELECT id, slug, name_fa
FROM products
WHERE name_normalized = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetProductByNormalizedNameRow struct {
	ID     int64
	Slug   string
	NameFa string
}

func (q *Queries) GetProductByNormalizedName(ctx context.Context, nameNormalized string) (GetProductByNormalizedNameRow, error) {
	row := q.db.QueryRow(ctx, getProductByNormalizedName, nameNormalized)
	var i GetProductByNormalizedNameRow
	err := row.Scan(&i.ID, &i.Slug, &i.NameFa)
	return i, err
}

const getProductLocks = `-- name: GetProductLocks :one
SELECT id, locked_fields, name_fa, name_en, generic_name, image_url, source_snapshot
FROM products
WHERE id = $1
  AND deleted_at IS NULL
`

type GetProductLocksRow struct {
	ID             int64
	LockedFields   []string
	NameFa         string
	NameEn         *string
	GenericName    *string
	ImageUrl       *string
	SourceSnapshot []byte
}

func (q *Queries) GetProductLocks(ctx context.Context, id int64) (GetProductLocksRow, error) {
	row := q.db.QueryRow(ctx, getProductLocks, id)
	var i GetProductLocksRow
	err := row.Scan(
		&i.ID,
		&i.LockedFields,
		&i.NameFa,
		&i.NameEn,
		&i.GenericName,
		&i.ImageUrl,
		&i.SourceSnapshot,
	)
	return i, err
}

const insertBrand = `-- name: InsertBrand :one
INSERT INTO brands (slug, name_fa, name_en)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertBrandParams struct {
	Slug   string
	NameFa string
	NameEn *string
}

func (q *Queries) InsertBrand(ctx context.Context, arg InsertBrandParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBrand, arg.Slug, arg.NameFa, arg.NameEn)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (slug, name_fa, name_en, image_url, brand_id, gtin, irc, status, name_normalized, search_document)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'published', $8, $9)
RETURNING id
`

type InsertProductParams struct {
	Slug           string
	NameFa         string
	NameEn         *string
	ImageUrl       *string
	BrandID        *int64
	Gtin           *string
	Irc            *string
	NameNormalized string
	SearchDocument string
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Slug,
		arg.NameFa,
		arg.NameEn,
		arg.ImageUrl,
		arg.BrandID,
		arg.Gtin,
		arg.Irc,
		arg.NameNormalized,
		arg.SearchDocument,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setProductSourceSnapshot = `-- name: SetProductSourceSnapshot :exec
UPDATE products
SET source_snapshot = $2
WHERE id = $1
`

type SetProductSourceSnapshotParams struct {
	ID             int64
	SourceSnapshot []byte
}

func (q *Queries) SetProductSourceSnapshot(ctx context.Context, arg SetProductSourceSnapshotParams) error {
	_, err := q.db.Exec(ctx, setProductSourceSnapshot, arg.ID, arg.SourceSnapshot)
	return err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (
    SELECT 1 FROM products WHERE slug = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProductFromSource = `-- name: UpdateProductFromSource :exec
UPDATE products
SET name_fa = CASE
                  WHEN 'name_fa' = ANY (locked_fields) THEN name_fa
                  ELSE $1
              END,
    name_en = CASE
                  WHEN 'name_en' = ANY (locked_fields) THEN name_en
                  ELSE $2
              END,
    image_url = CASE
                    WHEN 'image_url' = ANY (locked_fields) THEN image_url
                    ELSE $3
                END,
    source_snapshot = $4,
    name_normalized = CASE
                          WHEN 'name_fa' = ANY (locked_fields) THEN name_normalized
                          ELSE $5
                      END,
    search_document = CASE
                          WHEN 'name_fa' = ANY (locked_fields) THEN search_document
                          ELSE $6
                      END
WHERE id = $7
  AND deleted_at IS NULL
`

type UpdateProductFromSourceParams struct {
	NameFa         string
	NameEn         *string
	ImageUrl       *string
	SourceSnapshot []byte
	NameNormalized string
	SearchDocument string
	ID             int64
}

func (q *Queries) UpdateProductFromSource(ctx context.Context, arg UpdateProductFromSourceParams) error {
	_, err := q.db.Exec(ctx, updateProductFromSource,
		arg.NameFa,
		arg.NameEn,
		arg.ImageUrl,
		arg.SourceSnapshot,
		arg.NameNormalized,
		arg.SearchDocument,
		arg.ID,
	)
	return err
}
