// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"
	"time"
)

const consumeOTP = `-- name: ConsumeOTP :execrows
UPDATE otp_codes
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOTPSendsByIP = `-- name: CountOTPSendsByIP :one
SELECT COUNT(*)::bigint
FROM otp_sends
WHERE ip = $1
  AND created_at >= $2
`

type CountOTPSendsByIPParams struct {
	Ip        string
	CreatedAt time.Time
}

func (q *Queries) CountOTPSendsByIP(ctx context.Context, arg CountOTPSendsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOTPSendsByIP, arg.Ip, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOTPSendsByPhone = `-- name: CountOTPSendsByPhone :one
SELECT COUNT(*)::bigint
FROM otp_sends
WHERE phone = $1
  AND created_at >= $2
`

type CountOTPSendsByPhoneParams struct {
	Phone     string
	CreatedAt time.Time
}

func (q *Queries) CountOTPSendsByPhone(ctx context.Context, arg CountOTPSendsByPhoneParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOTPSendsByPhone, arg.Phone, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteUserSearches = `-- name: DeleteUserSearches :exec
DELETE FROM search_queries
WHERE user_id = $1
`

func (q *Queries) DeleteUserSearches(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, deleteUserSearches, userID)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteUserSession, tokenHash)
	return err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, phone, code_hash, expires_at, consumed_at, attempt_count, created_at
FROM otp_codes
WHERE phone = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPRow struct {
	ID           int64
	Phone        string
	CodeHash     string
	ExpiresAt    time.Time
	ConsumedAt   *time.Time
	AttemptCount int32
	CreatedAt    time.Time
}

func (q *Queries) GetLatestOTP(ctx context.Context, phone string) (GetLatestOTPRow, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, phone)
	var i GetLatestOTPRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, role
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID    int64
	Phone string
	Role  string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Phone, &i.Role)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, role
FROM users
WHERE phone = $1
  AND deleted_at IS NULL
`

type GetUserByPhoneRow struct {
	ID    int64
	Phone string
	Role  string
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(&i.ID, &i.Phone, &i.Role)
	return i, err
}

const getUserBySessionHash = `-- name: GetUserBySessionHash :one
SELECT u.id, u.phone, u.role, s.expires_at
FROM user_sessions s
         JOIN users u ON u.id = s.user_id AND u.deleted_at IS NULL
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetUserBySessionHashRow struct {
	ID        int64
	Phone     string
	Role      string
	ExpiresAt time.Time
}

func (q *Queries) GetUserBySessionHash(ctx context.Context, tokenHash string) (GetUserBySessionHashRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionHash, tokenHash)
	var i GetUserBySessionHashRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempt_count = attempt_count + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const insertOTPCode = `-- name: InsertOTPCode :one
INSERT INTO otp_codes (phone, code_hash, expires_at, ip)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertOTPCodeParams struct {
	Phone     string
	CodeHash  string
	ExpiresAt time.Time
	Ip        string
}

func (q *Queries) InsertOTPCode(ctx context.Context, arg InsertOTPCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOTPCode,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.Ip,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOTPSend = `-- name: InsertOTPSend :exec
INSERT INTO otp_sends (phone, ip)
VALUES ($1, $2)
`

type InsertOTPSendParams struct {
	Phone string
	Ip    string
}

func (q *Queries) InsertOTPSend(ctx context.Context, arg InsertOTPSendParams) error {
	_, err := q.db.Exec(ctx, insertOTPSend, arg.Phone, arg.Ip)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (phone)
VALUES ($1)
ON CONFLICT (phone) WHERE deleted_at IS NULL
DO UPDATE SET updated_at = now()
RETURNING id, phone, role
`

type InsertUserRow struct {
	ID    int64
	Phone string
	Role  string
}

func (q *Queries) InsertUser(ctx context.Context, phone string) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, phone)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.Phone, &i.Role)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertUserSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const listUserSearches = `-- name: ListUserSearches :many
SELECT id, queried_at, query_normalized, result_count
FROM search_queries
WHERE user_id = $1
ORDER BY queried_at DESC
LIMIT 50
`

type ListUserSearchesRow struct {
	ID              int64
	QueriedAt       time.Time
	QueryNormalized string
	ResultCount     int32
}

func (q *Queries) ListUserSearches(ctx context.Context, userID *int64) ([]ListUserSearchesRow, error) {
	rows, err := q.db.Query(ctx, listUserSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSearchesRow{}
	for rows.Next() {
		var i ListUserSearchesRow
		if err := rows.Scan(
			&i.ID,
			&i.QueriedAt,
			&i.QueryNormalized,
			&i.ResultCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
