// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMatchCandidate = `-- name: InsertMatchCandidate :exec
INSERT INTO match_candidates (source_item_id, suggested_product_id, score, status, reason)
VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT (source_item_id) WHERE status = 'pending'
    DO UPDATE SET suggested_product_id = EXCLUDED.suggested_product_id,
                  score                = EXCLUDED.score,
                  reason               = EXCLUDED.reason
`

type InsertMatchCandidateParams struct {
	SourceItemID       int64
	SuggestedProductID *int64
	Score              pgtype.Numeric
	Reason             string
}

func (q *Queries) InsertMatchCandidate(ctx context.Context, arg InsertMatchCandidateParams) error {
	_, err := q.db.Exec(ctx, insertMatchCandidate,
		arg.SourceItemID,
		arg.SuggestedProductID,
		arg.Score,
		arg.Reason,
	)
	return err
}

const linkSourceItemProduct = `-- name: LinkSourceItemProduct :exec
UPDATE source_items
SET product_id = $2
WHERE id = $1
`

type LinkSourceItemProductParams struct {
	ID        int64
	ProductID *int64
}

func (q *Queries) LinkSourceItemProduct(ctx context.Context, arg LinkSourceItemProductParams) error {
	_, err := q.db.Exec(ctx, linkSourceItemProduct, arg.ID, arg.ProductID)
	return err
}

const upsertSourceItem = `-- name: UpsertSourceItem :one
INSERT INTO source_items (source_id, external_id, product_id, raw, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (source_id, external_id)
    DO UPDATE SET raw        = EXCLUDED.raw,
                  fetched_at = EXCLUDED.fetched_at,
                  product_id = COALESCE(source_items.product_id, EXCLUDED.product_id)
RETURNING id, product_id
`

type UpsertSourceItemParams struct {
	SourceID   int64
	ExternalID string
	ProductID  *int64
	Raw        []byte
}

type UpsertSourceItemRow struct {
	ID        int64
	ProductID *int64
}

func (q *Queries) UpsertSourceItem(ctx context.Context, arg UpsertSourceItemParams) (UpsertSourceItemRow, error) {
	row := q.db.QueryRow(ctx, upsertSourceItem,
		arg.SourceID,
		arg.ExternalID,
		arg.ProductID,
		arg.Raw,
	)
	var i UpsertSourceItemRow
	err := row.Scan(&i.ID, &i.ProductID)
	return i, err
}
