// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"
	"time"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running',
    attempts = attempts + 1,
    updated_at = now()
WHERE id = (
    SELECT id
    FROM jobs
    WHERE status IN ('pending', 'retry')
      AND run_at <= now()
    ORDER BY run_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, payload, status, attempts, max_attempts, run_at, last_error
`

type ClaimJobRow struct {
	ID          int64
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int32
	MaxAttempts int32
	RunAt       time.Time
	LastError   *string
}

func (q *Queries) ClaimJob(ctx context.Context) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LastError,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'succeeded',
    last_error = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (kind, payload, max_attempts, run_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type EnqueueJobParams struct {
	Kind        string
	Payload     []byte
	MaxAttempts int32
	RunAt       time.Time
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.Payload,
		arg.MaxAttempts,
		arg.RunAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status = $1,
    run_at = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $4
`

type FailJobParams struct {
	Status    string
	RunAt     time.Time
	LastError *string
	ID        int64
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob,
		arg.Status,
		arg.RunAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const hasOpenJob = `-- name: HasOpenJob :one
SELECT EXISTS (
    SELECT 1
    FROM jobs
    WHERE kind = $1
      AND payload->>'source_id' = $2::text
      AND status IN ('pending', 'retry', 'running')
) AS exists
`

type HasOpenJobParams struct {
	Kind     string
	SourceID string
}

func (q *Queries) HasOpenJob(ctx context.Context, arg HasOpenJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenJob, arg.Kind, arg.SourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasOpenJobByKind = `-- name: HasOpenJobByKind :one
SELECT EXISTS (
    SELECT 1
    FROM jobs
    WHERE kind = $1
      AND status IN ('pending', 'retry', 'running')
) AS exists
`

func (q *Queries) HasOpenJobByKind(ctx context.Context, kind string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenJobByKind, kind)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
