// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Brand struct {
	ID        int64
	Slug      string
	NameFa    string
	NameEn    *string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Category struct {
	ID        int64
	ParentID  *int64
	Slug      string
	NameFa    string
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type DataSource struct {
	ID               int64
	PharmacyID       int64
	Kind             string
	Config           []byte
	ScheduleInterval time.Duration
	IsEnabled        bool
	LastRunAt        *time.Time
	LastStatus       *string
	LastError        *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
}

type Offer struct {
	ID           int64
	ProductID    int64
	PharmacyID   int64
	SourceItemID *int64
	PriceRial    int64
	InStock      bool
	ProductUrl   string
	Status       string
	LastSeenAt   time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Pharmacy struct {
	ID         int64
	Slug       string
	Name       string
	SiteDomain string
	LogoUrl    *string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  *time.Time
}

type PriceHistory struct {
	ID         int64
	OfferID    int64
	ProductID  int64
	PharmacyID int64
	PriceRial  int64
	InStock    bool
	RecordedAt time.Time
}

type Product struct {
	ID          int64
	Slug        string
	NameFa      string
	NameEn      *string
	GenericName *string
	DosageForm  *string
	Strength    *string
	BrandID     *int64
	CategoryID  *int64
	ImageUrl    *string
	Description *string
	Gtin        *string
	Irc         *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type SourceItem struct {
	ID         int64
	SourceID   int64
	ExternalID string
	ProductID  *int64
	Raw        []byte
	FetchedAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
