// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package store

import (
	"context"
	"time"
)

const getOfferByProductPharmacy = `-- name: GetOfferByProductPharmacy :one
SELECT id, price_rial, in_stock, status
FROM offers
WHERE product_id = $1
  AND pharmacy_id = $2
`

type GetOfferByProductPharmacyParams struct {
	ProductID  int64
	PharmacyID int64
}

type GetOfferByProductPharmacyRow struct {
	ID        int64
	PriceRial int64
	InStock   bool
	Status    string
}

func (q *Queries) GetOfferByProductPharmacy(ctx context.Context, arg GetOfferByProductPharmacyParams) (GetOfferByProductPharmacyRow, error) {
	row := q.db.QueryRow(ctx, getOfferByProductPharmacy, arg.ProductID, arg.PharmacyID)
	var i GetOfferByProductPharmacyRow
	err := row.Scan(
		&i.ID,
		&i.PriceRial,
		&i.InStock,
		&i.Status,
	)
	return i, err
}

const insertPriceHistory = `-- name: InsertPriceHistory :exec
INSERT INTO price_history (offer_id, product_id, pharmacy_id, price_rial, in_stock)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPriceHistoryParams struct {
	OfferID    int64
	ProductID  int64
	PharmacyID int64
	PriceRial  int64
	InStock    bool
}

func (q *Queries) InsertPriceHistory(ctx context.Context, arg InsertPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPriceHistory,
		arg.OfferID,
		arg.ProductID,
		arg.PharmacyID,
		arg.PriceRial,
		arg.InStock,
	)
	return err
}

const listActiveOffersByProduct = `-- name: ListActiveOffersByProduct :many
SELECT o.id,
       o.price_rial,
       o.in_stock,
       o.product_url,
       o.last_seen_at,
       o.status,
       ph.name AS pharmacy_name,
       ph.slug AS pharmacy_slug
FROM offers o
         JOIN pharmacies ph ON ph.id = o.pharmacy_id AND ph.deleted_at IS NULL
WHERE o.product_id = $1
  AND o.status = 'active'
ORDER BY o.price_rial ASC, o.last_seen_at DESC
`

type ListActiveOffersByProductRow struct {
	ID           int64
	PriceRial    int64
	InStock      bool
	ProductUrl   string
	LastSeenAt   time.Time
	Status       string
	PharmacyName string
	PharmacySlug string
}

func (q *Queries) ListActiveOffersByProduct(ctx context.Context, productID int64) ([]ListActiveOffersByProductRow, error) {
	rows, err := q.db.Query(ctx, listActiveOffersByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOffersByProductRow{}
	for rows.Next() {
		var i ListActiveOffersByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.PriceRial,
			&i.InStock,
			&i.ProductUrl,
			&i.LastSeenAt,
			&i.Status,
			&i.PharmacyName,
			&i.PharmacySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOfferSuspicious = `-- name: MarkOfferSuspicious :exec
UPDATE offers
SET status              = 'suspicious',
    proposed_price_rial = $2,
    proposed_at         = now(),
    last_seen_at        = now(),
    in_stock            = $3,
    product_url         = $4,
    source_item_id      = $5
WHERE id = $1
`

type MarkOfferSuspiciousParams struct {
	ID                int64
	ProposedPriceRial *int64
	InStock           bool
	ProductUrl        string
	SourceItemID      *int64
}

func (q *Queries) MarkOfferSuspicious(ctx context.Context, arg MarkOfferSuspiciousParams) error {
	_, err := q.db.Exec(ctx, markOfferSuspicious,
		arg.ID,
		arg.ProposedPriceRial,
		arg.InStock,
		arg.ProductUrl,
		arg.SourceItemID,
	)
	return err
}

const upsertOffer = `-- name: UpsertOffer :one
INSERT INTO offers (product_id, pharmacy_id, source_item_id, price_rial, in_stock, product_url, status, last_seen_at,
                    proposed_price_rial, proposed_at)
VALUES ($1, $2, $3, $4, $5, $6, 'active', now(), NULL, NULL)
ON CONFLICT (product_id, pharmacy_id)
    DO UPDATE SET source_item_id       = EXCLUDED.source_item_id,
                  price_rial           = EXCLUDED.price_rial,
                  in_stock             = EXCLUDED.in_stock,
                  product_url          = EXCLUDED.product_url,
                  last_seen_at         = now(),
                  status               = 'active',
                  proposed_price_rial  = NULL,
                  proposed_at          = NULL
RETURNING id, price_rial, in_stock
`

type UpsertOfferParams struct {
	ProductID    int64
	PharmacyID   int64
	SourceItemID *int64
	PriceRial    int64
	InStock      bool
	ProductUrl   string
}

type UpsertOfferRow struct {
	ID        int64
	PriceRial int64
	InStock   bool
}

func (q *Queries) UpsertOffer(ctx context.Context, arg UpsertOfferParams) (UpsertOfferRow, error) {
	row := q.db.QueryRow(ctx, upsertOffer,
		arg.ProductID,
		arg.PharmacyID,
		arg.SourceItemID,
		arg.PriceRial,
		arg.InStock,
		arg.ProductUrl,
	)
	var i UpsertOfferRow
	err := row.Scan(&i.ID, &i.PriceRial, &i.InStock)
	return i, err
}
