// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_health.sql

package store

import (
	"context"
	"time"
)

const approveSuspiciousOffer = `-- name: ApproveSuspiciousOffer :one
UPDATE offers
SET price_rial          = proposed_price_rial,
    status              = 'active',
    proposed_price_rial = NULL,
    proposed_at         = NULL
WHERE id = $1
  AND status = 'suspicious'
  AND proposed_price_rial IS NOT NULL
RETURNING id, product_id, pharmacy_id, price_rial, in_stock
`

type ApproveSuspiciousOfferRow struct {
	ID         int64
	ProductID  int64
	PharmacyID int64
	PriceRial  int64
	InStock    bool
}

func (q *Queries) ApproveSuspiciousOffer(ctx context.Context, id int64) (ApproveSuspiciousOfferRow, error) {
	row := q.db.QueryRow(ctx, approveSuspiciousOffer, id)
	var i ApproveSuspiciousOfferRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.PharmacyID,
		&i.PriceRial,
		&i.InStock,
	)
	return i, err
}

const countSuspiciousOffers = `-- name: CountSuspiciousOffers :one
SELECT COUNT(*)::bigint
FROM offers
WHERE status = 'suspicious'
`

func (q *Queries) CountSuspiciousOffers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuspiciousOffers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSuspiciousOffer = `-- name: GetSuspiciousOffer :one
SELECT o.id,
       o.product_id,
       o.pharmacy_id,
       o.price_rial,
       o.proposed_price_rial,
       o.proposed_at,
       o.status,
       o.in_stock,
       o.source_item_id,
       COALESCE(si.source_id, 0)::bigint AS source_id
FROM offers o
         LEFT JOIN source_items si ON si.id = o.source_item_id
WHERE o.id = $1
`

type GetSuspiciousOfferRow struct {
	ID                int64
	ProductID         int64
	PharmacyID        int64
	PriceRial         int64
	ProposedPriceRial *int64
	ProposedAt        *time.Time
	Status            string
	InStock           bool
	SourceItemID      *int64
	SourceID          int64
}

func (q *Queries) GetSuspiciousOffer(ctx context.Context, id int64) (GetSuspiciousOfferRow, error) {
	row := q.db.QueryRow(ctx, getSuspiciousOffer, id)
	var i GetSuspiciousOfferRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.PharmacyID,
		&i.PriceRial,
		&i.ProposedPriceRial,
		&i.ProposedAt,
		&i.Status,
		&i.InStock,
		&i.SourceItemID,
		&i.SourceID,
	)
	return i, err
}

const incrementSourcePriceRejects = `-- name: IncrementSourcePriceRejects :exec
UPDATE data_sources
SET price_reject_count = price_reject_count + 1
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) IncrementSourcePriceRejects(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementSourcePriceRejects, id)
	return err
}

const listSourceHealth = `-- name: ListSourceHealth :many
SELECT ds.id,
       ds.pharmacy_id,
       ph.name  AS pharmacy_name,
       ph.slug  AS pharmacy_slug,
       ds.kind,
       ds.schedule_interval::text AS schedule_interval,
       ds.is_enabled,
       ds.last_run_at,
       ds.last_status,
       ds.last_error,
       ds.price_reject_count,
       COALESCE(sr.id, 0)::bigint         AS run_id,
       COALESCE(sr.status, '')::text      AS run_status,
       COALESCE(sr.started_at, TIMESTAMPTZ 'epoch') AS run_started_at,
       sr.finished_at                     AS run_finished_at,
       COALESCE(sr.ok_count, 0)::int      AS run_ok_count,
       COALESCE(sr.fail_count, 0)::int    AS run_fail_count,
       sr.error                           AS run_error
FROM data_sources ds
         JOIN pharmacies ph ON ph.id = ds.pharmacy_id AND ph.deleted_at IS NULL
         LEFT JOIN LATERAL (
    SELECT id, status, started_at, finished_at, ok_count, fail_count, error
    FROM sync_runs r
    WHERE r.source_id = ds.id
    ORDER BY r.started_at DESC
    LIMIT 1
    ) sr ON TRUE
WHERE ds.deleted_at IS NULL
ORDER BY ph.name, ds.id
`

type ListSourceHealthRow struct {
	ID               int64
	PharmacyID       int64
	PharmacyName     string
	PharmacySlug     string
	Kind             string
	ScheduleInterval string
	IsEnabled        bool
	LastRunAt        *time.Time
	LastStatus       *string
	LastError        *string
	PriceRejectCount int32
	RunID            int64
	RunStatus        string
	RunStartedAt     time.Time
	RunFinishedAt    *time.Time
	RunOkCount       int32
	RunFailCount     int32
	RunError         *string
}

func (q *Queries) ListSourceHealth(ctx context.Context) ([]ListSourceHealthRow, error) {
	rows, err := q.db.Query(ctx, listSourceHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceHealthRow{}
	for rows.Next() {
		var i ListSourceHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.PharmacyName,
			&i.PharmacySlug,
			&i.Kind,
			&i.ScheduleInterval,
			&i.IsEnabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
			&i.PriceRejectCount,
			&i.RunID,
			&i.RunStatus,
			&i.RunStartedAt,
			&i.RunFinishedAt,
			&i.RunOkCount,
			&i.RunFailCount,
			&i.RunError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceSyncRuns = `-- name: ListSourceSyncRuns :many
SELECT id, status, started_at, finished_at, ok_count, fail_count, error
FROM sync_runs
WHERE source_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListSourceSyncRunsParams struct {
	SourceID  int64
	PageLimit int32
}

type ListSourceSyncRunsRow struct {
	ID         int64
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
	OkCount    int32
	FailCount  int32
	Error      *string
}

func (q *Queries) ListSourceSyncRuns(ctx context.Context, arg ListSourceSyncRunsParams) ([]ListSourceSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listSourceSyncRuns, arg.SourceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceSyncRunsRow{}
	for rows.Next() {
		var i ListSourceSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OkCount,
			&i.FailCount,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSources = `-- name: ListStaleSources :many
SELECT ds.id,
       ph.name AS pharmacy_name,
       ph.slug AS pharmacy_slug,
       MIN(o.last_seen_at)::timestamptz AS oldest_seen,
       COUNT(o.id)::int    AS offer_count
FROM data_sources ds
         JOIN pharmacies ph ON ph.id = ds.pharmacy_id AND ph.deleted_at IS NULL
         JOIN offers o ON o.pharmacy_id = ds.pharmacy_id AND o.status = 'active'
WHERE ds.deleted_at IS NULL
GROUP BY ds.id, ph.name, ph.slug
ORDER BY MIN(o.last_seen_at) ASC
`

type ListStaleSourcesRow struct {
	ID           int64
	PharmacyName string
	PharmacySlug string
	OldestSeen   time.Time
	OfferCount   int32
}

func (q *Queries) ListStaleSources(ctx context.Context) ([]ListStaleSourcesRow, error) {
	rows, err := q.db.Query(ctx, listStaleSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSourcesRow{}
	for rows.Next() {
		var i ListStaleSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyName,
			&i.PharmacySlug,
			&i.OldestSeen,
			&i.OfferCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuspiciousOffers = `-- name: ListSuspiciousOffers :many
SELECT o.id,
       o.product_id,
       o.pharmacy_id,
       o.price_rial,
       o.proposed_price_rial,
       o.proposed_at,
       o.product_url,
       o.last_seen_at,
       o.in_stock,
       p.slug      AS product_slug,
       p.name_fa   AS product_name,
       ph.name     AS pharmacy_name,
       ph.slug     AS pharmacy_slug,
       COALESCE(si.source_id, 0)::bigint AS source_id,
       COALESCE(ds.price_reject_count, 0)::int AS source_reject_count
FROM offers o
         JOIN products p ON p.id = o.product_id AND p.deleted_at IS NULL
         JOIN pharmacies ph ON ph.id = o.pharmacy_id AND ph.deleted_at IS NULL
         LEFT JOIN source_items si ON si.id = o.source_item_id
         LEFT JOIN data_sources ds ON ds.id = si.source_id AND ds.deleted_at IS NULL
WHERE o.status = 'suspicious'
ORDER BY o.proposed_at DESC NULLS LAST, o.id
LIMIT $2 OFFSET $1
`

type ListSuspiciousOffersParams struct {
	PageOffset int32
	PageLimit  int32
}

type ListSuspiciousOffersRow struct {
	ID                int64
	ProductID         int64
	PharmacyID        int64
	PriceRial         int64
	ProposedPriceRial *int64
	ProposedAt        *time.Time
	ProductUrl        string
	LastSeenAt        time.Time
	InStock           bool
	ProductSlug       string
	ProductName       string
	PharmacyName      string
	PharmacySlug      string
	SourceID          int64
	SourceRejectCount int32
}

func (q *Queries) ListSuspiciousOffers(ctx context.Context, arg ListSuspiciousOffersParams) ([]ListSuspiciousOffersRow, error) {
	rows, err := q.db.Query(ctx, listSuspiciousOffers, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuspiciousOffersRow{}
	for rows.Next() {
		var i ListSuspiciousOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.PharmacyID,
			&i.PriceRial,
			&i.ProposedPriceRial,
			&i.ProposedAt,
			&i.ProductUrl,
			&i.LastSeenAt,
			&i.InStock,
			&i.ProductSlug,
			&i.ProductName,
			&i.PharmacyName,
			&i.PharmacySlug,
			&i.SourceID,
			&i.SourceRejectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncSuccessRates = `-- name: ListSyncSuccessRates :many
SELECT source_id,
       COUNT(*)::int                                              AS runs,
       COUNT(*) FILTER (WHERE status = 'succeeded')::int          AS succeeded,
       COUNT(*) FILTER (WHERE status = 'failed')::int             AS failed
FROM sync_runs
WHERE started_at >= $1
  AND ($2::bigint = 0 OR source_id = $2)
GROUP BY source_id
`

type ListSyncSuccessRatesParams struct {
	Since    time.Time
	SourceID int64
}

type ListSyncSuccessRatesRow struct {
	SourceID  int64
	Runs      int32
	Succeeded int32
	Failed    int32
}

func (q *Queries) ListSyncSuccessRates(ctx context.Context, arg ListSyncSuccessRatesParams) ([]ListSyncSuccessRatesRow, error) {
	rows, err := q.db.Query(ctx, listSyncSuccessRates, arg.Since, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncSuccessRatesRow{}
	for rows.Next() {
		var i ListSyncSuccessRatesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Runs,
			&i.Succeeded,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectSuspiciousOffer = `-- name: RejectSuspiciousOffer :exec
UPDATE offers
SET status              = 'active',
    proposed_price_rial = NULL,
    proposed_at         = NULL
WHERE id = $1
  AND status = 'suspicious'
`

func (q *Queries) RejectSuspiciousOffer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, rejectSuspiciousOffer, id)
	return err
}
