// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_auth.sql

package store

import (
	"context"
	"time"
)

const countRecentLoginAttempts = `-- name: CountRecentLoginAttempts :one
SELECT COUNT(*)::bigint AS n
FROM login_attempts
WHERE attempted_at >= $1
  AND (username = $2 OR ip = $3)
`

type CountRecentLoginAttemptsParams struct {
	Since    time.Time
	Username string
	Ip       string
}

func (q *Queries) CountRecentLoginAttempts(ctx context.Context, arg CountRecentLoginAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentLoginAttempts, arg.Since, arg.Username, arg.Ip)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM internal_sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM internal_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getInternalUserByID = `-- name: GetInternalUserByID :one
SELECT id, username, role, is_active
FROM internal_users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetInternalUserByIDRow struct {
	ID       int64
	Username string
	Role     string
	IsActive bool
}

func (q *Queries) GetInternalUserByID(ctx context.Context, id int64) (GetInternalUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getInternalUserByID, id)
	var i GetInternalUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getInternalUserByUsername = `-- name: GetInternalUserByUsername :one
SELECT id, username, password_hash, role, is_active
FROM internal_users
WHERE username = $1
  AND deleted_at IS NULL
`

type GetInternalUserByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
	Role         string
	IsActive     bool
}

func (q *Queries) GetInternalUserByUsername(ctx context.Context, username string) (GetInternalUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getInternalUserByUsername, username)
	var i GetInternalUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.role, u.is_active, s.expires_at
FROM internal_sessions s
         JOIN internal_users u ON u.id = s.user_id AND u.deleted_at IS NULL
WHERE s.token_hash = $1
`

type GetSessionUserRow struct {
	ID        int64
	Username  string
	Role      string
	IsActive  bool
	ExpiresAt time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.ExpiresAt,
	)
	return i, err
}

const insertInternalUser = `-- name: InsertInternalUser :one
INSERT INTO internal_users (username, password_hash, role, is_active)
VALUES ($1, $2, $3, TRUE)
RETURNING id
`

type InsertInternalUserParams struct {
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) InsertInternalUser(ctx context.Context, arg InsertInternalUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInternalUser, arg.Username, arg.PasswordHash, arg.Role)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (username, ip)
VALUES ($1, $2)
`

type InsertLoginAttemptParams struct {
	Username string
	Ip       string
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt, arg.Username, arg.Ip)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO internal_sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
