// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_sources.sql

package store

import (
	"context"
	"time"
)

const disableDataSource = `-- name: DisableDataSource :exec
UPDATE data_sources
SET is_enabled = FALSE,
    deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DisableDataSource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableDataSource, id)
	return err
}

const disablePharmacy = `-- name: DisablePharmacy :exec
UPDATE pharmacies
SET status     = 'disabled',
    deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DisablePharmacy(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disablePharmacy, id)
	return err
}

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT id, status, started_at, finished_at, ok_count, fail_count, error
FROM sync_runs
WHERE source_id = $1
ORDER BY started_at DESC
LIMIT 1
`

type GetLatestSyncRunRow struct {
	ID         int64
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
	OkCount    int32
	FailCount  int32
	Error      *string
}

func (q *Queries) GetLatestSyncRun(ctx context.Context, sourceID int64) (GetLatestSyncRunRow, error) {
	row := q.db.QueryRow(ctx, getLatestSyncRun, sourceID)
	var i GetLatestSyncRunRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OkCount,
		&i.FailCount,
		&i.Error,
	)
	return i, err
}

const getOpsPharmacy = `-- name: GetOpsPharmacy :one
SELECT id, slug, name, site_domain, logo_url, status
FROM pharmacies
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOpsPharmacyRow struct {
	ID         int64
	Slug       string
	Name       string
	SiteDomain string
	LogoUrl    *string
	Status     string
}

func (q *Queries) GetOpsPharmacy(ctx context.Context, id int64) (GetOpsPharmacyRow, error) {
	row := q.db.QueryRow(ctx, getOpsPharmacy, id)
	var i GetOpsPharmacyRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SiteDomain,
		&i.LogoUrl,
		&i.Status,
	)
	return i, err
}

const getOpsSource = `-- name: GetOpsSource :one
SELECT ds.id,
       ds.pharmacy_id,
       p.name        AS pharmacy_name,
       p.slug        AS pharmacy_slug,
       ds.kind,
       ds.config,
       ds.schedule_interval::text AS schedule_interval,
       ds.is_enabled,
       ds.last_run_at,
       ds.last_status,
       ds.last_error
FROM data_sources ds
         JOIN pharmacies p ON p.id = ds.pharmacy_id
WHERE ds.id = $1
  AND ds.deleted_at IS NULL
`

type GetOpsSourceRow struct {
	ID               int64
	PharmacyID       int64
	PharmacyName     string
	PharmacySlug     string
	Kind             string
	Config           []byte
	ScheduleInterval string
	IsEnabled        bool
	LastRunAt        *time.Time
	LastStatus       *string
	LastError        *string
}

func (q *Queries) GetOpsSource(ctx context.Context, id int64) (GetOpsSourceRow, error) {
	row := q.db.QueryRow(ctx, getOpsSource, id)
	var i GetOpsSourceRow
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.PharmacyName,
		&i.PharmacySlug,
		&i.Kind,
		&i.Config,
		&i.ScheduleInterval,
		&i.IsEnabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastError,
	)
	return i, err
}

const insertDataSource = `-- name: InsertDataSource :one
INSERT INTO data_sources (pharmacy_id, kind, config, schedule_interval, is_enabled)
VALUES ($1, $2, $3, CAST($4 AS text)::interval, TRUE)
RETURNING id
`

type InsertDataSourceParams struct {
	PharmacyID       int64
	Kind             string
	Config           []byte
	ScheduleInterval string
}

func (q *Queries) InsertDataSource(ctx context.Context, arg InsertDataSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDataSource,
		arg.PharmacyID,
		arg.Kind,
		arg.Config,
		arg.ScheduleInterval,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPharmacy = `-- name: InsertPharmacy :one
INSERT INTO pharmacies (slug, name, site_domain, logo_url, status)
VALUES ($1, $2, $3, $4, 'active')
RETURNING id
`

type InsertPharmacyParams struct {
	Slug       string
	Name       string
	SiteDomain string
	LogoUrl    *string
}

func (q *Queries) InsertPharmacy(ctx context.Context, arg InsertPharmacyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPharmacy,
		arg.Slug,
		arg.Name,
		arg.SiteDomain,
		arg.LogoUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpsPharmacies = `-- name: ListOpsPharmacies :many
SELECT id, slug, name, site_domain, logo_url, status
FROM pharmacies
WHERE deleted_at IS NULL
ORDER BY name
`

type ListOpsPharmaciesRow struct {
	ID         int64
	Slug       string
	Name       string
	SiteDomain string
	LogoUrl    *string
	Status     string
}

func (q *Queries) ListOpsPharmacies(ctx context.Context) ([]ListOpsPharmaciesRow, error) {
	rows, err := q.db.Query(ctx, listOpsPharmacies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsPharmaciesRow{}
	for rows.Next() {
		var i ListOpsPharmaciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SiteDomain,
			&i.LogoUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsSources = `-- name: ListOpsSources :many
SELECT ds.id,
       ds.pharmacy_id,
       p.name        AS pharmacy_name,
       p.slug        AS pharmacy_slug,
       ds.kind,
       ds.config,
       ds.schedule_interval::text AS schedule_interval,
       ds.is_enabled,
       ds.last_run_at,
       ds.last_status,
       ds.last_error
FROM data_sources ds
         JOIN pharmacies p ON p.id = ds.pharmacy_id
WHERE ds.deleted_at IS NULL
ORDER BY ds.id
`

type ListOpsSourcesRow struct {
	ID               int64
	PharmacyID       int64
	PharmacyName     string
	PharmacySlug     string
	Kind             string
	Config           []byte
	ScheduleInterval string
	IsEnabled        bool
	LastRunAt        *time.Time
	LastStatus       *string
	LastError        *string
}

func (q *Queries) ListOpsSources(ctx context.Context) ([]ListOpsSourcesRow, error) {
	rows, err := q.db.Query(ctx, listOpsSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsSourcesRow{}
	for rows.Next() {
		var i ListOpsSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.PharmacyName,
			&i.PharmacySlug,
			&i.Kind,
			&i.Config,
			&i.ScheduleInterval,
			&i.IsEnabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceJobs = `-- name: ListSourceJobs :many
SELECT id, kind, status, attempts, max_attempts, run_at, last_error, created_at
FROM jobs
WHERE kind = 'sync_source'
  AND payload->>'source_id' = $1::text
ORDER BY created_at DESC
LIMIT 20
`

type ListSourceJobsRow struct {
	ID          int64
	Kind        string
	Status      string
	Attempts    int32
	MaxAttempts int32
	RunAt       time.Time
	LastError   *string
	CreatedAt   time.Time
}

func (q *Queries) ListSourceJobs(ctx context.Context, sourceID string) ([]ListSourceJobsRow, error) {
	rows, err := q.db.Query(ctx, listSourceJobs, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceJobsRow{}
	for rows.Next() {
		var i ListSourceJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataSource = `-- name: UpdateDataSource :exec
UPDATE data_sources
SET kind              = $1,
    config            = $2,
    schedule_interval = CAST($3 AS text)::interval,
    is_enabled        = $4
WHERE id = $5
  AND deleted_at IS NULL
`

type UpdateDataSourceParams struct {
	Kind             string
	Config           []byte
	ScheduleInterval string
	IsEnabled        bool
	ID               int64
}

func (q *Queries) UpdateDataSource(ctx context.Context, arg UpdateDataSourceParams) error {
	_, err := q.db.Exec(ctx, updateDataSource,
		arg.Kind,
		arg.Config,
		arg.ScheduleInterval,
		arg.IsEnabled,
		arg.ID,
	)
	return err
}

const updatePharmacy = `-- name: UpdatePharmacy :exec
UPDATE pharmacies
SET name        = $1,
    site_domain = $2,
    logo_url    = $3,
    status      = $4
WHERE id = $5
  AND deleted_at IS NULL
`

type UpdatePharmacyParams struct {
	Name       string
	SiteDomain string
	LogoUrl    *string
	Status     string
	ID         int64
}

func (q *Queries) UpdatePharmacy(ctx context.Context, arg UpdatePharmacyParams) error {
	_, err := q.db.Exec(ctx, updatePharmacy,
		arg.Name,
		arg.SiteDomain,
		arg.LogoUrl,
		arg.Status,
		arg.ID,
	)
	return err
}
