// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_audit.sql

package store

import (
	"context"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)::bigint AS n
FROM audit_logs
WHERE ($1::bigint = 0 OR actor_id = $1)
  AND created_at >= $2
  AND created_at < $3
`

type CountAuditLogsParams struct {
	ActorID int64
	Since   time.Time
	Until   time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.ActorID, arg.Since, arg.Until)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, actor_name, entity, entity_id, action, before_data, after_data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ActorID    *int64
	ActorName  string
	Entity     string
	EntityID   string
	Action     string
	BeforeData []byte
	AfterData  []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.ActorName,
		arg.Entity,
		arg.EntityID,
		arg.Action,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_name, entity, entity_id, action, before_data, after_data, created_at
FROM audit_logs
WHERE ($1::bigint = 0 OR actor_id = $1)
  AND created_at >= $2
  AND created_at < $3
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListAuditLogsParams struct {
	ActorID    int64
	Since      time.Time
	Until      time.Time
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorID,
		arg.Since,
		arg.Until,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Entity,
			&i.EntityID,
			&i.Action,
			&i.BeforeData,
			&i.AfterData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
