// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_match.sql

package store

import (
	"context"
	"time"
)

const countMatchPendingKPI = `-- name: CountMatchPendingKPI :one
SELECT COUNT(*)::bigint AS n
FROM match_candidates
WHERE status = 'pending'
`

func (q *Queries) CountMatchPendingKPI(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchPendingKPI)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countPendingMatches = `-- name: CountPendingMatches :one
SELECT COUNT(*)::bigint AS n
FROM match_candidates mc
         JOIN source_items si ON si.id = mc.source_item_id
WHERE mc.status = 'pending'
  AND ($1::bigint = 0 OR si.source_id = $1)
  AND ($2::float8 <= 0 OR COALESCE(mc.score, 0)::float8 >= $2)
`

type CountPendingMatchesParams struct {
	SourceID int64
	MinScore float64
}

func (q *Queries) CountPendingMatches(ctx context.Context, arg CountPendingMatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingMatches, arg.SourceID, arg.MinScore)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const decideMatchCandidate = `-- name: DecideMatchCandidate :exec
UPDATE match_candidates
SET status              = $1,
    decided_by          = $2,
    decided_at          = now(),
    previous_product_id = $3,
    linked_product_id   = $4,
    suggested_product_id = COALESCE($5, suggested_product_id)
WHERE id = $6
`

type DecideMatchCandidateParams struct {
	Status             string
	DecidedBy          *int64
	PreviousProductID  *int64
	LinkedProductID    *int64
	SuggestedProductID *int64
	ID                 int64
}

func (q *Queries) DecideMatchCandidate(ctx context.Context, arg DecideMatchCandidateParams) error {
	_, err := q.db.Exec(ctx, decideMatchCandidate,
		arg.Status,
		arg.DecidedBy,
		arg.PreviousProductID,
		arg.LinkedProductID,
		arg.SuggestedProductID,
		arg.ID,
	)
	return err
}

const deleteOffer = `-- name: DeleteOffer :exec
DELETE FROM offers
WHERE id = $1
`

func (q *Queries) DeleteOffer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOffer, id)
	return err
}

const getMatchCandidate = `-- name: GetMatchCandidate :one
SELECT mc.id,
       mc.source_item_id,
       mc.suggested_product_id,
       COALESCE(mc.score, 0)::float8 AS score,
       mc.status,
       mc.reason,
       mc.previous_product_id,
       mc.linked_product_id,
       si.source_id,
       si.external_id,
       si.raw,
       si.product_id AS current_product_id,
       ds.pharmacy_id
FROM match_candidates mc
         JOIN source_items si ON si.id = mc.source_item_id
         JOIN data_sources ds ON ds.id = si.source_id
WHERE mc.id = $1
`

type GetMatchCandidateRow struct {
	ID                 int64
	SourceItemID       int64
	SuggestedProductID *int64
	Score              float64
	Status             string
	Reason             string
	PreviousProductID  *int64
	LinkedProductID    *int64
	SourceID           int64
	ExternalID         string
	Raw                []byte
	CurrentProductID   *int64
	PharmacyID         int64
}

func (q *Queries) GetMatchCandidate(ctx context.Context, id int64) (GetMatchCandidateRow, error) {
	row := q.db.QueryRow(ctx, getMatchCandidate, id)
	var i GetMatchCandidateRow
	err := row.Scan(
		&i.ID,
		&i.SourceItemID,
		&i.SuggestedProductID,
		&i.Score,
		&i.Status,
		&i.Reason,
		&i.PreviousProductID,
		&i.LinkedProductID,
		&i.SourceID,
		&i.ExternalID,
		&i.Raw,
		&i.CurrentProductID,
		&i.PharmacyID,
	)
	return i, err
}

const getOfferBySourceItem = `-- name: GetOfferBySourceItem :one
SELECT id, product_id, pharmacy_id, price_rial, in_stock, product_url, status
FROM offers
WHERE source_item_id = $1
LIMIT 1
`

type GetOfferBySourceItemRow struct {
	ID         int64
	ProductID  int64
	PharmacyID int64
	PriceRial  int64
	InStock    bool
	ProductUrl string
	Status     string
}

func (q *Queries) GetOfferBySourceItem(ctx context.Context, sourceItemID *int64) (GetOfferBySourceItemRow, error) {
	row := q.db.QueryRow(ctx, getOfferBySourceItem, sourceItemID)
	var i GetOfferBySourceItemRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.PharmacyID,
		&i.PriceRial,
		&i.InStock,
		&i.ProductUrl,
		&i.Status,
	)
	return i, err
}

const getSourceItemByID = `-- name: GetSourceItemByID :one
SELECT id, source_id, external_id, product_id, raw
FROM source_items
WHERE id = $1
`

type GetSourceItemByIDRow struct {
	ID         int64
	SourceID   int64
	ExternalID string
	ProductID  *int64
	Raw        []byte
}

func (q *Queries) GetSourceItemByID(ctx context.Context, id int64) (GetSourceItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getSourceItemByID, id)
	var i GetSourceItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.ProductID,
		&i.Raw,
	)
	return i, err
}

const listPendingMatches = `-- name: ListPendingMatches :many
SELECT mc.id,
       mc.source_item_id,
       mc.suggested_product_id,
       COALESCE(mc.score, 0)::float8 AS score,
       mc.status,
       mc.reason,
       mc.created_at,
       si.source_id,
       si.external_id,
       si.raw,
       si.product_id    AS current_product_id,
       p.slug           AS suggested_slug,
       p.name_fa        AS suggested_name,
       p.image_url      AS suggested_image
FROM match_candidates mc
         JOIN source_items si ON si.id = mc.source_item_id
         LEFT JOIN products p ON p.id = mc.suggested_product_id AND p.deleted_at IS NULL
WHERE mc.status = 'pending'
  AND ($1::bigint = 0 OR si.source_id = $1)
  AND ($2::float8 <= 0 OR COALESCE(mc.score, 0)::float8 >= $2)
ORDER BY mc.score DESC NULLS LAST, mc.created_at ASC
LIMIT $4
OFFSET $3
`

type ListPendingMatchesParams struct {
	SourceID   int64
	MinScore   float64
	PageOffset int32
	PageLimit  int32
}

type ListPendingMatchesRow struct {
	ID                 int64
	SourceItemID       int64
	SuggestedProductID *int64
	Score              float64
	Status             string
	Reason             string
	CreatedAt          time.Time
	SourceID           int64
	ExternalID         string
	Raw                []byte
	CurrentProductID   *int64
	SuggestedSlug      *string
	SuggestedName      *string
	SuggestedImage     *string
}

func (q *Queries) ListPendingMatches(ctx context.Context, arg ListPendingMatchesParams) ([]ListPendingMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPendingMatches,
		arg.SourceID,
		arg.MinScore,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingMatchesRow{}
	for rows.Next() {
		var i ListPendingMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.SuggestedProductID,
			&i.Score,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.SourceID,
			&i.ExternalID,
			&i.Raw,
			&i.CurrentProductID,
			&i.SuggestedSlug,
			&i.SuggestedName,
			&i.SuggestedImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relinkOfferProduct = `-- name: RelinkOfferProduct :exec
UPDATE offers
SET product_id = $1
WHERE id = $2
`

type RelinkOfferProductParams struct {
	ProductID int64
	ID        int64
}

func (q *Queries) RelinkOfferProduct(ctx context.Context, arg RelinkOfferProductParams) error {
	_, err := q.db.Exec(ctx, relinkOfferProduct, arg.ProductID, arg.ID)
	return err
}

const reopenMatchCandidate = `-- name: ReopenMatchCandidate :exec
UPDATE match_candidates
SET status     = 'pending',
    decided_by = NULL,
    decided_at = NULL
WHERE id = $1
`

func (q *Queries) ReopenMatchCandidate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, reopenMatchCandidate, id)
	return err
}
