// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_clicks.sql

package store

import (
	"context"
	"time"
)

const countClicksInRange = `-- name: CountClicksInRange :one

SELECT COUNT(*)::bigint
FROM redirect_clicks
WHERE clicked_at >= $1
  AND clicked_at < $2
`

type CountClicksInRangeParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

// Click reports filter on clicked_at so Postgres can prune monthly partitions.
func (q *Queries) CountClicksInRange(ctx context.Context, arg CountClicksInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksInRange, arg.RangeStart, arg.RangeEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listClicksByPharmacy = `-- name: ListClicksByPharmacy :many
SELECT ph.id,
       ph.slug,
       ph.name,
       COUNT(*)::bigint AS clicks
FROM redirect_clicks rc
         JOIN pharmacies ph ON ph.id = rc.pharmacy_id AND ph.deleted_at IS NULL
WHERE rc.clicked_at >= $1
  AND rc.clicked_at < $2
GROUP BY ph.id, ph.slug, ph.name
ORDER BY clicks DESC, ph.name
`

type ListClicksByPharmacyParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListClicksByPharmacyRow struct {
	ID     int64
	Slug   string
	Name   string
	Clicks int64
}

func (q *Queries) ListClicksByPharmacy(ctx context.Context, arg ListClicksByPharmacyParams) ([]ListClicksByPharmacyRow, error) {
	rows, err := q.db.Query(ctx, listClicksByPharmacy, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClicksByPharmacyRow{}
	for rows.Next() {
		var i ListClicksByPharmacyRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopClickedProducts = `-- name: ListTopClickedProducts :many
SELECT p.id,
       p.slug,
       p.name_fa,
       COUNT(*)::bigint AS clicks
FROM redirect_clicks rc
         JOIN products p ON p.id = rc.product_id AND p.deleted_at IS NULL
WHERE rc.clicked_at >= $1
  AND rc.clicked_at < $2
GROUP BY p.id, p.slug, p.name_fa
ORDER BY clicks DESC, p.name_fa
LIMIT 20
`

type ListTopClickedProductsParams struct {
	RangeStart time.Time
	RangeEnd   time.Time
}

type ListTopClickedProductsRow struct {
	ID     int64
	Slug   string
	NameFa string
	Clicks int64
}

func (q *Queries) ListTopClickedProducts(ctx context.Context, arg ListTopClickedProductsParams) ([]ListTopClickedProductsRow, error) {
	rows, err := q.db.Query(ctx, listTopClickedProducts, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopClickedProductsRow{}
	for rows.Next() {
		var i ListTopClickedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
