// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops_catalog.sql

package store

import (
	"context"
	"time"
)

const countBrandProducts = `-- name: CountBrandProducts :one
SELECT COUNT(*)::bigint AS n
FROM products
WHERE brand_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountBrandProducts(ctx context.Context, brandID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBrandProducts, brandID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countCategoryChildren = `-- name: CountCategoryChildren :one
SELECT COUNT(*)::bigint AS n
FROM categories
WHERE parent_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountCategoryChildren(ctx context.Context, parentID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryChildren, parentID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countCategoryProducts = `-- name: CountCategoryProducts :one
SELECT COUNT(*)::bigint AS n
FROM products
WHERE category_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountCategoryProducts(ctx context.Context, categoryID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryProducts, categoryID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countOpsProducts = `-- name: CountOpsProducts :one
SELECT COUNT(*)::bigint AS n
FROM products
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR name_fa ILIKE '%' || $2 || '%')
`

type CountOpsProductsParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountOpsProducts(ctx context.Context, arg CountOpsProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpsProducts, arg.Status, arg.Q)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const getCategoryRedirect = `-- name: GetCategoryRedirect :one
SELECT old_slug, category_id
FROM category_slug_redirects
WHERE old_slug = $1
`

type GetCategoryRedirectRow struct {
	OldSlug    string
	CategoryID int64
}

func (q *Queries) GetCategoryRedirect(ctx context.Context, oldSlug string) (GetCategoryRedirectRow, error) {
	row := q.db.QueryRow(ctx, getCategoryRedirect, oldSlug)
	var i GetCategoryRedirectRow
	err := row.Scan(&i.OldSlug, &i.CategoryID)
	return i, err
}

const getOpsBrand = `-- name: GetOpsBrand :one
SELECT id, slug, name_fa, name_en
FROM brands
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOpsBrandRow struct {
	ID     int64
	Slug   string
	NameFa string
	NameEn *string
}

func (q *Queries) GetOpsBrand(ctx context.Context, id int64) (GetOpsBrandRow, error) {
	row := q.db.QueryRow(ctx, getOpsBrand, id)
	var i GetOpsBrandRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameFa,
		&i.NameEn,
	)
	return i, err
}

const getOpsCategory = `-- name: GetOpsCategory :one
SELECT id, parent_id, slug, name_fa, position
FROM categories
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOpsCategoryRow struct {
	ID       int64
	ParentID *int64
	Slug     string
	NameFa   string
	Position int32
}

func (q *Queries) GetOpsCategory(ctx context.Context, id int64) (GetOpsCategoryRow, error) {
	row := q.db.QueryRow(ctx, getOpsCategory, id)
	var i GetOpsCategoryRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameFa,
		&i.Position,
	)
	return i, err
}

const getOpsCategoryBySlug = `-- name: GetOpsCategoryBySlug :one
SELECT id, parent_id, slug, name_fa, position
FROM categories
WHERE slug = $1
  AND deleted_at IS NULL
`

type GetOpsCategoryBySlugRow struct {
	ID       int64
	ParentID *int64
	Slug     string
	NameFa   string
	Position int32
}

func (q *Queries) GetOpsCategoryBySlug(ctx context.Context, slug string) (GetOpsCategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getOpsCategoryBySlug, slug)
	var i GetOpsCategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameFa,
		&i.Position,
	)
	return i, err
}

const getOpsProduct = `-- name: GetOpsProduct :one
SELECT p.id,
       p.slug,
       p.name_fa,
       p.name_en,
       p.generic_name,
       p.gtin,
       p.irc,
       p.brand_id,
       p.category_id,
       p.image_url,
       p.status,
       p.locked_fields,
       p.source_snapshot,
       b.slug    AS brand_slug,
       b.name_fa AS brand_name,
       c.slug    AS category_slug,
       c.name_fa AS category_name
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetOpsProductRow struct {
	ID             int64
	Slug           string
	NameFa         string
	NameEn         *string
	GenericName    *string
	Gtin           *string
	Irc            *string
	BrandID        *int64
	CategoryID     *int64
	ImageUrl       *string
	Status         string
	LockedFields   []string
	SourceSnapshot []byte
	BrandSlug      *string
	BrandName      *string
	CategorySlug   *string
	CategoryName   *string
}

func (q *Queries) GetOpsProduct(ctx context.Context, id int64) (GetOpsProductRow, error) {
	row := q.db.QueryRow(ctx, getOpsProduct, id)
	var i GetOpsProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameFa,
		&i.NameEn,
		&i.GenericName,
		&i.Gtin,
		&i.Irc,
		&i.BrandID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.Status,
		&i.LockedFields,
		&i.SourceSnapshot,
		&i.BrandSlug,
		&i.BrandName,
		&i.CategorySlug,
		&i.CategoryName,
	)
	return i, err
}

const insertCategorySlugRedirect = `-- name: InsertCategorySlugRedirect :exec
INSERT INTO category_slug_redirects (old_slug, category_id)
VALUES ($1, $2)
ON CONFLICT (old_slug) DO UPDATE SET category_id = EXCLUDED.category_id
`

type InsertCategorySlugRedirectParams struct {
	OldSlug    string
	CategoryID int64
}

func (q *Queries) InsertCategorySlugRedirect(ctx context.Context, arg InsertCategorySlugRedirectParams) error {
	_, err := q.db.Exec(ctx, insertCategorySlugRedirect, arg.OldSlug, arg.CategoryID)
	return err
}

const insertOpsBrand = `-- name: InsertOpsBrand :one
INSERT INTO brands (slug, name_fa, name_en)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertOpsBrandParams struct {
	Slug   string
	NameFa string
	NameEn *string
}

func (q *Queries) InsertOpsBrand(ctx context.Context, arg InsertOpsBrandParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOpsBrand, arg.Slug, arg.NameFa, arg.NameEn)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOpsCategory = `-- name: InsertOpsCategory :one
INSERT INTO categories (parent_id, slug, name_fa, position)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertOpsCategoryParams struct {
	ParentID *int64
	Slug     string
	NameFa   string
	Position int32
}

func (q *Queries) InsertOpsCategory(ctx context.Context, arg InsertOpsCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOpsCategory,
		arg.ParentID,
		arg.Slug,
		arg.NameFa,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpsBrands = `-- name: ListOpsBrands :many
SELECT id, slug, name_fa, name_en
FROM brands
WHERE deleted_at IS NULL
ORDER BY name_fa
`

type ListOpsBrandsRow struct {
	ID     int64
	Slug   string
	NameFa string
	NameEn *string
}

func (q *Queries) ListOpsBrands(ctx context.Context) ([]ListOpsBrandsRow, error) {
	rows, err := q.db.Query(ctx, listOpsBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsBrandsRow{}
	for rows.Next() {
		var i ListOpsBrandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.NameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsCategories = `-- name: ListOpsCategories :many
SELECT id, parent_id, slug, name_fa, position
FROM categories
WHERE deleted_at IS NULL
ORDER BY position, name_fa
`

type ListOpsCategoriesRow struct {
	ID       int64
	ParentID *int64
	Slug     string
	NameFa   string
	Position int32
}

func (q *Queries) ListOpsCategories(ctx context.Context) ([]ListOpsCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listOpsCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsCategoriesRow{}
	for rows.Next() {
		var i ListOpsCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.NameFa,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpsProducts = `-- name: ListOpsProducts :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.status,
       p.image_url,
       p.locked_fields,
       b.name_fa AS brand_name,
       c.name_fa AS category_name
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.status = $1)
  AND ($2::text IS NULL OR p.name_fa ILIKE '%' || $2 || '%')
ORDER BY p.updated_at DESC
LIMIT $4
OFFSET $3
`

type ListOpsProductsParams struct {
	Status     *string
	Q          *string
	PageOffset int32
	PageLimit  int32
}

type ListOpsProductsRow struct {
	ID           int64
	Slug         string
	NameFa       string
	Status       string
	ImageUrl     *string
	LockedFields []string
	BrandName    *string
	CategoryName *string
}

func (q *Queries) ListOpsProducts(ctx context.Context, arg ListOpsProductsParams) ([]ListOpsProductsRow, error) {
	rows, err := q.db.Query(ctx, listOpsProducts,
		arg.Status,
		arg.Q,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpsProductsRow{}
	for rows.Next() {
		var i ListOpsProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.Status,
			&i.ImageUrl,
			&i.LockedFields,
			&i.BrandName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSlugs = `-- name: ListPublishedSlugs :many
SELECT slug, updated_at
FROM products
WHERE status = 'published'
  AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT 50000
`

type ListPublishedSlugsRow struct {
	Slug      string
	UpdatedAt time.Time
}

func (q *Queries) ListPublishedSlugs(ctx context.Context) ([]ListPublishedSlugsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedSlugsRow{}
	for rows.Next() {
		var i ListPublishedSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignBrandProducts = `-- name: ReassignBrandProducts :exec
UPDATE products
SET brand_id = $1
WHERE brand_id = $2
  AND deleted_at IS NULL
`

type ReassignBrandProductsParams struct {
	NewID *int64
	OldID *int64
}

func (q *Queries) ReassignBrandProducts(ctx context.Context, arg ReassignBrandProductsParams) error {
	_, err := q.db.Exec(ctx, reassignBrandProducts, arg.NewID, arg.OldID)
	return err
}

const reassignCategoryProducts = `-- name: ReassignCategoryProducts :exec
UPDATE products
SET category_id = $1
WHERE category_id = $2
  AND deleted_at IS NULL
`

type ReassignCategoryProductsParams struct {
	NewID *int64
	OldID *int64
}

func (q *Queries) ReassignCategoryProducts(ctx context.Context, arg ReassignCategoryProductsParams) error {
	_, err := q.db.Exec(ctx, reassignCategoryProducts, arg.NewID, arg.OldID)
	return err
}

const softDeleteBrand = `-- name: SoftDeleteBrand :exec
UPDATE brands
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBrand(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteBrand, id)
	return err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const updateOpsBrand = `-- name: UpdateOpsBrand :exec
UPDATE brands
SET slug    = $1,
    name_fa = $2,
    name_en = $3
WHERE id = $4
  AND deleted_at IS NULL
`

type UpdateOpsBrandParams struct {
	Slug   string
	NameFa string
	NameEn *string
	ID     int64
}

func (q *Queries) UpdateOpsBrand(ctx context.Context, arg UpdateOpsBrandParams) error {
	_, err := q.db.Exec(ctx, updateOpsBrand,
		arg.Slug,
		arg.NameFa,
		arg.NameEn,
		arg.ID,
	)
	return err
}

const updateOpsCategory = `-- name: UpdateOpsCategory :exec
UPDATE categories
SET parent_id = $1,
    slug      = $2,
    name_fa   = $3,
    position  = $4
WHERE id = $5
  AND deleted_at IS NULL
`

type UpdateOpsCategoryParams struct {
	ParentID *int64
	Slug     string
	NameFa   string
	Position int32
	ID       int64
}

func (q *Queries) UpdateOpsCategory(ctx context.Context, arg UpdateOpsCategoryParams) error {
	_, err := q.db.Exec(ctx, updateOpsCategory,
		arg.ParentID,
		arg.Slug,
		arg.NameFa,
		arg.Position,
		arg.ID,
	)
	return err
}

const updateOpsProduct = `-- name: UpdateOpsProduct :exec
UPDATE products
SET name_fa          = $1,
    name_en          = $2,
    generic_name     = $3,
    brand_id         = $4,
    category_id      = $5,
    image_url        = $6,
    status           = $7,
    locked_fields    = $8,
    source_snapshot  = $9,
    name_normalized  = $10,
    search_document  = $11
WHERE id = $12
  AND deleted_at IS NULL
`

type UpdateOpsProductParams struct {
	NameFa         string
	NameEn         *string
	GenericName    *string
	BrandID        *int64
	CategoryID     *int64
	ImageUrl       *string
	Status         string
	LockedFields   []string
	SourceSnapshot []byte
	NameNormalized string
	SearchDocument string
	ID             int64
}

func (q *Queries) UpdateOpsProduct(ctx context.Context, arg UpdateOpsProductParams) error {
	_, err := q.db.Exec(ctx, updateOpsProduct,
		arg.NameFa,
		arg.NameEn,
		arg.GenericName,
		arg.BrandID,
		arg.CategoryID,
		arg.ImageUrl,
		arg.Status,
		arg.LockedFields,
		arg.SourceSnapshot,
		arg.NameNormalized,
		arg.SearchDocument,
		arg.ID,
	)
	return err
}
