// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package store

import (
	"context"
	"time"
)

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id,
       p.slug,
       p.name_fa,
       p.name_en,
       p.generic_name,
       p.dosage_form,
       p.strength,
       p.image_url,
       p.description,
       p.status,
       p.updated_at,
       b.name_fa AS brand_name,
       c.name_fa AS category_name
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.slug = $1
  AND p.deleted_at IS NULL
  AND p.status = 'published'
`

type GetProductBySlugRow struct {
	ID           int64
	Slug         string
	NameFa       string
	NameEn       *string
	GenericName  *string
	DosageForm   *string
	Strength     *string
	ImageUrl     *string
	Description  *string
	Status       string
	UpdatedAt    time.Time
	BrandName    *string
	CategoryName *string
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameFa,
		&i.NameEn,
		&i.GenericName,
		&i.DosageForm,
		&i.Strength,
		&i.ImageUrl,
		&i.Description,
		&i.Status,
		&i.UpdatedAt,
		&i.BrandName,
		&i.CategoryName,
	)
	return i, err
}
