// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
}

var _ Querier = (*Queries)(nil)
