// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redirect.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureRedirectClicksMonth = `-- name: EnsureRedirectClicksMonth :exec
SELECT ensure_redirect_clicks_month($1::date)
`

func (q *Queries) EnsureRedirectClicksMonth(ctx context.Context, monthStart pgtype.Date) error {
	_, err := q.db.Exec(ctx, ensureRedirectClicksMonth, monthStart)
	return err
}

const getActiveOfferByID = `-- name: GetActiveOfferByID :one
SELECT o.id,
       o.product_id,
       o.pharmacy_id,
       o.product_url,
       o.status
FROM offers o
WHERE o.id = $1
  AND o.status = 'active'
`

type GetActiveOfferByIDRow struct {
	ID         int64
	ProductID  int64
	PharmacyID int64
	ProductUrl string
	Status     string
}

func (q *Queries) GetActiveOfferByID(ctx context.Context, id int64) (GetActiveOfferByIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveOfferByID, id)
	var i GetActiveOfferByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.PharmacyID,
		&i.ProductUrl,
		&i.Status,
	)
	return i, err
}

const insertRedirectClick = `-- name: InsertRedirectClick :exec
INSERT INTO redirect_clicks (offer_id, product_id, pharmacy_id, referrer)
VALUES ($1, $2, $3, $4)
`

type InsertRedirectClickParams struct {
	OfferID    int64
	ProductID  int64
	PharmacyID int64
	Referrer   *string
}

func (q *Queries) InsertRedirectClick(ctx context.Context, arg InsertRedirectClickParams) error {
	_, err := q.db.Exec(ctx, insertRedirectClick,
		arg.OfferID,
		arg.ProductID,
		arg.PharmacyID,
		arg.Referrer,
	)
	return err
}
