// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"time"
)

const countSearchProducts = `-- name: CountSearchProducts :one
WITH cfg AS (
    SELECT set_limit($6::real) AS lim
)
SELECT COUNT(*)::bigint AS total_count
FROM cfg,
     products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND (
            p.name_normalized = $1
        OR p.name_normalized LIKE $1 || '%'
        OR p.search_document LIKE '%' || $1 || '%'
        OR p.search_document OPERATOR (public.%) $1
    )
  AND ($2::text = '' OR b.slug = $2)
  AND ($3::text = '' OR c.slug = $3)
  AND (
            NOT $4::bool
        OR EXISTS (SELECT 1
                   FROM offers ox
                   WHERE ox.product_id = p.id
                     AND ox.status = 'active'
                     AND ox.last_seen_at >= $5
                     AND ox.in_stock)
    )
`

type CountSearchProductsParams struct {
	Q            string
	BrandSlug    string
	CategorySlug string
	InStockOnly  bool
	FreshSince   time.Time
	SimLimit     float32
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts,
		arg.Q,
		arg.BrandSlug,
		arg.CategorySlug,
		arg.InStockOnly,
		arg.FreshSince,
		arg.SimLimit,
	)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const insertSearchQuery = `-- name: InsertSearchQuery :exec
INSERT INTO search_queries (query_normalized, result_count, duration_ms, user_id)
VALUES ($1, $2, $3, $4)
`

type InsertSearchQueryParams struct {
	QueryNormalized string
	ResultCount     int32
	DurationMs      int32
	UserID          *int64
}

func (q *Queries) InsertSearchQuery(ctx context.Context, arg InsertSearchQueryParams) error {
	_, err := q.db.Exec(ctx, insertSearchQuery,
		arg.QueryNormalized,
		arg.ResultCount,
		arg.DurationMs,
		arg.UserID,
	)
	return err
}

const listFrequentSearches = `-- name: ListFrequentSearches :many
SELECT query_normalized, COUNT(*)::bigint AS hits, MAX(queried_at) AS last_seen
FROM search_queries
WHERE queried_at >= $1
GROUP BY query_normalized
ORDER BY hits DESC, last_seen DESC
LIMIT 50
`

type ListFrequentSearchesRow struct {
	QueryNormalized string
	Hits            int64
	LastSeen        interface{}
}

func (q *Queries) ListFrequentSearches(ctx context.Context, since time.Time) ([]ListFrequentSearchesRow, error) {
	rows, err := q.db.Query(ctx, listFrequentSearches, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrequentSearchesRow{}
	for rows.Next() {
		var i ListFrequentSearchesRow
		if err := rows.Scan(&i.QueryNormalized, &i.Hits, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchBrands = `-- name: ListSearchBrands :many
SELECT b.slug, b.name_fa
FROM brands b
WHERE b.deleted_at IS NULL
  AND EXISTS (SELECT 1
              FROM products p
              WHERE p.brand_id = b.id
                AND p.deleted_at IS NULL
                AND p.status = 'published')
ORDER BY b.name_fa
LIMIT 80
`

type ListSearchBrandsRow struct {
	Slug   string
	NameFa string
}

func (q *Queries) ListSearchBrands(ctx context.Context) ([]ListSearchBrandsRow, error) {
	rows, err := q.db.Query(ctx, listSearchBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchBrandsRow{}
	for rows.Next() {
		var i ListSearchBrandsRow
		if err := rows.Scan(&i.Slug, &i.NameFa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchCategories = `-- name: ListSearchCategories :many
SELECT c.slug, c.name_fa
FROM categories c
WHERE c.deleted_at IS NULL
  AND EXISTS (SELECT 1
              FROM products p
              WHERE p.category_id = c.id
                AND p.deleted_at IS NULL
                AND p.status = 'published')
ORDER BY c.name_fa
LIMIT 80
`

type ListSearchCategoriesRow struct {
	Slug   string
	NameFa string
}

func (q *Queries) ListSearchCategories(ctx context.Context) ([]ListSearchCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listSearchCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchCategoriesRow{}
	for rows.Next() {
		var i ListSearchCategoriesRow
		if err := rows.Scan(&i.Slug, &i.NameFa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZeroResultSearches = `-- name: ListZeroResultSearches :many
SELECT query_normalized, COUNT(*)::bigint AS hits, MAX(queried_at) AS last_seen
FROM search_queries
WHERE result_count = 0
  AND queried_at >= $1
GROUP BY query_normalized
ORDER BY hits DESC, last_seen DESC
LIMIT 50
`

type ListZeroResultSearchesRow struct {
	QueryNormalized string
	Hits            int64
	LastSeen        interface{}
}

func (q *Queries) ListZeroResultSearches(ctx context.Context, since time.Time) ([]ListZeroResultSearchesRow, error) {
	rows, err := q.db.Query(ctx, listZeroResultSearches, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZeroResultSearchesRow{}
	for rows.Next() {
		var i ListZeroResultSearchesRow
		if err := rows.Scan(&i.QueryNormalized, &i.Hits, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE((SELECT MIN(o.price_rial) FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       (SELECT COUNT(*)::int FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1) AS offer_count,
       (SELECT COUNT(*)::int FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock) AS in_stock_count,
       similarity(p.search_document, $2)::float8 AS sim
FROM products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND ($3::text = '' OR b.slug = $3)
  AND ($4::text = '' OR c.slug = $4)
  AND (
            NOT $5::bool
        OR EXISTS (SELECT 1
                   FROM offers ox
                   WHERE ox.product_id = p.id
                     AND ox.status = 'active'
                     AND ox.last_seen_at >= $1
                     AND ox.in_stock)
    )
ORDER BY p.search_document <-> $2
LIMIT $7
OFFSET $6
`

type SearchProductsParams struct {
	FreshSince   time.Time
	Q            string
	BrandSlug    string
	CategorySlug string
	InStockOnly  bool
	PageOffset   int32
	PageLimit    int32
}

type SearchProductsRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
	Sim             float64
}

// GiST KNN (document <-> query) with LIMIT, no selective WHERE on the
// document: an unselective %/LIKE clause would force a seq scan of the
// whole catalogue. The caller keeps rows with sim >= MinSimilarity.
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.FreshSince,
		arg.Q,
		arg.BrandSlug,
		arg.CategorySlug,
		arg.InStockOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByPrice = `-- name: SearchProductsByPrice :many
WITH cfg AS (
    SELECT set_limit($9::real) AS lim
)
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1)::int AS offer_count,
       COUNT(o.id) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock)::int AS in_stock_count
FROM cfg,
     products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
         LEFT JOIN offers o ON o.product_id = p.id
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND (
            p.name_normalized = $2
        OR p.name_normalized LIKE $2 || '%'
        OR p.search_document LIKE '%' || $2 || '%'
        OR p.search_document OPERATOR (public.%) $2
    )
  AND ($3::text = '' OR b.slug = $3)
  AND ($4::text = '' OR c.slug = $4)
  AND (
            NOT $5::bool
        OR EXISTS (SELECT 1
                   FROM offers ox
                   WHERE ox.product_id = p.id
                     AND ox.status = 'active'
                     AND ox.last_seen_at >= $1
                     AND ox.in_stock)
    )
GROUP BY p.id, b.name_fa
ORDER BY
    CASE WHEN $6::text = 'price_asc' THEN COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0) END ASC NULLS LAST,
    CASE WHEN $6::text = 'price_desc' THEN COALESCE(MIN(o.price_rial) FILTER (WHERE o.status = 'active' AND o.last_seen_at >= $1), 0) END DESC NULLS LAST,
    p.id
LIMIT $8
OFFSET $7
`

type SearchProductsByPriceParams struct {
	FreshSince   time.Time
	Q            string
	BrandSlug    string
	CategorySlug string
	InStockOnly  bool
	Sort         string
	PageOffset   int32
	PageLimit    int32
	SimLimit     float32
}

type SearchProductsByPriceRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
}

func (q *Queries) SearchProductsByPrice(ctx context.Context, arg SearchProductsByPriceParams) ([]SearchProductsByPriceRow, error) {
	rows, err := q.db.Query(ctx, searchProductsByPrice,
		arg.FreshSince,
		arg.Q,
		arg.BrandSlug,
		arg.CategorySlug,
		arg.InStockOnly,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
		arg.SimLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsByPriceRow{}
	for rows.Next() {
		var i SearchProductsByPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsMatched = `-- name: SearchProductsMatched :many
WITH cfg AS (
    SELECT set_limit($8::real) AS lim
)
SELECT p.id,
       p.slug,
       p.name_fa,
       p.image_url,
       b.name_fa AS brand_name,
       COALESCE((SELECT MIN(o.price_rial) FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1), 0)::bigint AS lowest_price_rial,
       (SELECT COUNT(*)::int FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1) AS offer_count,
       (SELECT COUNT(*)::int FROM offers o WHERE o.product_id = p.id AND o.status = 'active' AND o.last_seen_at >= $1 AND o.in_stock) AS in_stock_count
FROM cfg,
     products p
         LEFT JOIN brands b ON b.id = p.brand_id AND b.deleted_at IS NULL
         LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
  AND (
            p.name_normalized = $2
        OR p.name_normalized LIKE $2 || '%'
        OR p.search_document LIKE '%' || $2 || '%'
        OR p.search_document OPERATOR (public.%) $2
    )
  AND ($3::text = '' OR b.slug = $3)
  AND ($4::text = '' OR c.slug = $4)
  AND (
            NOT $5::bool
        OR EXISTS (SELECT 1
                   FROM offers ox
                   WHERE ox.product_id = p.id
                     AND ox.status = 'active'
                     AND ox.last_seen_at >= $1
                     AND ox.in_stock)
    )
ORDER BY
    CASE
        WHEN p.name_normalized = $2 THEN 0
        WHEN p.name_normalized LIKE $2 || '%' THEN 1
        WHEN p.search_document LIKE $2 || '%' THEN 2
        ELSE 3
        END,
    p.search_document OPERATOR (public.<->) $2,
    p.id
LIMIT $7
OFFSET $6
`

type SearchProductsMatchedParams struct {
	FreshSince   time.Time
	Q            string
	BrandSlug    string
	CategorySlug string
	InStockOnly  bool
	PageOffset   int32
	PageLimit    int32
	SimLimit     float32
}

type SearchProductsMatchedRow struct {
	ID              int64
	Slug            string
	NameFa          string
	ImageUrl        *string
	BrandName       *string
	LowestPriceRial int64
	OfferCount      int32
	InStockCount    int32
}

// Used when the match set is small enough that a GIN-filtered scan plus
// sort beats an unfiltered KNN pass (short distinctive queries).
func (q *Queries) SearchProductsMatched(ctx context.Context, arg SearchProductsMatchedParams) ([]SearchProductsMatchedRow, error) {
	rows, err := q.db.Query(ctx, searchProductsMatched,
		arg.FreshSince,
		arg.Q,
		arg.BrandSlug,
		arg.CategorySlug,
		arg.InStockOnly,
		arg.PageOffset,
		arg.PageLimit,
		arg.SimLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsMatchedRow{}
	for rows.Next() {
		var i SearchProductsMatchedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameFa,
			&i.ImageUrl,
			&i.BrandName,
			&i.LowestPriceRial,
			&i.OfferCount,
			&i.InStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
