// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package store

import (
	"context"
)

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at = now(),
    status = $1,
    ok_count = $2,
    fail_count = $3,
    error = $4
WHERE id = $5
`

type FinishSyncRunParams struct {
	Status    string
	OkCount   int32
	FailCount int32
	Error     *string
	ID        int64
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.Status,
		arg.OkCount,
		arg.FailCount,
		arg.Error,
		arg.ID,
	)
	return err
}

const getDataSource = `-- name: GetDataSource :one
SELECT ds.id,
       ds.pharmacy_id,
       ds.kind,
       ds.config,
       ds.is_enabled
FROM data_sources ds
WHERE ds.id = $1
  AND ds.deleted_at IS NULL
`

type GetDataSourceRow struct {
	ID         int64
	PharmacyID int64
	Kind       string
	Config     []byte
	IsEnabled  bool
}

func (q *Queries) GetDataSource(ctx context.Context, id int64) (GetDataSourceRow, error) {
	row := q.db.QueryRow(ctx, getDataSource, id)
	var i GetDataSourceRow
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.Kind,
		&i.Config,
		&i.IsEnabled,
	)
	return i, err
}

const insertSyncRun = `-- name: InsertSyncRun :one
INSERT INTO sync_runs (source_id, status)
VALUES ($1, 'running')
RETURNING id
`

func (q *Queries) InsertSyncRun(ctx context.Context, sourceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, insertSyncRun, sourceID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDueSources = `-- name: ListDueSources :many
SELECT ds.id,
       ds.pharmacy_id,
       ds.kind,
       ds.config,
       ds.is_enabled
FROM data_sources ds
WHERE ds.deleted_at IS NULL
  AND ds.is_enabled
  AND (ds.last_run_at IS NULL
    OR ds.last_run_at + ds.schedule_interval <= now())
`

type ListDueSourcesRow struct {
	ID         int64
	PharmacyID int64
	Kind       string
	Config     []byte
	IsEnabled  bool
}

func (q *Queries) ListDueSources(ctx context.Context) ([]ListDueSourcesRow, error) {
	rows, err := q.db.Query(ctx, listDueSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueSourcesRow{}
	for rows.Next() {
		var i ListDueSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.Kind,
			&i.Config,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourceRun = `-- name: MarkSourceRun :exec
UPDATE data_sources
SET last_run_at = now(),
    last_status = $1,
    last_error = $2
WHERE id = $3
`

type MarkSourceRunParams struct {
	LastStatus *string
	LastError  *string
	ID         int64
}

func (q *Queries) MarkSourceRun(ctx context.Context, arg MarkSourceRunParams) error {
	_, err := q.db.Exec(ctx, markSourceRun, arg.LastStatus, arg.LastError, arg.ID)
	return err
}
